import ZhangLS.Spec.ActualGramUniformLittleO

/-! Exact defining-module ownership, full elaborated types, and transitive axioms.
Run this audit with the existing compiled dependency closure; no Lake invocation
or repository/cache writes are needed. The private output contains full types.
-/
set_option autoImplicit false
set_option maxHeartbeats 24000000
set_option maxRecDepth 10000
set_option pp.all true
set_option pp.privateNames true
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.maxSteps 10000000
set_option pp.universes true

open Lean Elab Command in
run_cmd do
  let env ← getEnv
  let moduleNames := env.header.moduleNames
  let out ← IO.getStdout
  let owners : Array Name := #[
    `ZhangLS.Spec.ActualGramUniformAssembly,
    `ZhangLS.Spec.ActualGramUniformBudget,
    `ZhangLS.Spec.ActualGramUniformEnvelopes,
    `ZhangLS.Spec.ActualGramUniformGeometry,
    `ZhangLS.Spec.ActualGramUniformLittleO,
    `ZhangLS.Spec.ActualGramUniformSubstitution
  ]
  let expectedPublic : Array (Name × Name) := #[
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniformArithmeticResidual),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniform_assembled_error),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniform_smooth_data),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformResidualConstant),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformWeightConstant),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_decay_comparison),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_four_term_comparison),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_residual_constant_nonneg),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_residual_quantitative),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformExponent),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformFirstBoundaryConstant),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformMainConstant),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformSecondBoundaryConstant),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_first_boundary_bound),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_first_boundary_constant_pos),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_main_constant_pos),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_pi_bound),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_scale_bounds),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_second_boundary_bound),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_second_boundary_constant_pos),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniformPairs),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_harmonic_bound),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_pair_geometry),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_pairs_subset),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_support_ceiling),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_logT_tenth),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_residual_little_o),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_smooth_residual_little_o),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformFirstError),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformFirstNorm),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformSecondError),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformSecondMain),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_envelopes_nonneg),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds)
  ]
  let expectedOwned : Array (Name × Name) := #[
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.C),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData._sizeOf_1),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData._sizeOf_inst),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.b),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.casesOn),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.ctorIdx),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.f),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.f'),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.f''),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.g),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.g'),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.g''),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hC),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hb),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hb0),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hf),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hf'),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hf''),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hf0),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hfd),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hfp0),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hfpz),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hft),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hfz),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hg),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hg'),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hg''),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hg0),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hg1),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hgd),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hgt),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.hgz),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.mk),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.mk._flat_ctor),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.mk.inj),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.mk.injEq),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.mk.noConfusion),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.mk.sizeOf_spec),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.noConfusion),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.noConfusionType),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.rec),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.ActualGramUniformProfileData.recOn),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramProfileProductResidual.eq_1),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniformArithmeticResidual),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniformPairs.eq_1),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniform_assembled_error),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniform_assembled_error._proof_1_1),
    (`ZhangLS.Spec.ActualGramUniformAssembly, `ZhangLS.Spec.actualGramUniform_smooth_data),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformResidualConstant),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformResidualConstant._proof_1),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformResidualConstant._proof_2),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformWeightConstant),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformWeightConstant._proof_1),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniformWeightConstant._proof_2),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_decay_comparison),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_decay_comparison._proof_1_1),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_decay_comparison._proof_1_2),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_decay_comparison._proof_1_3),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_four_term_comparison),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_residual_constant_nonneg),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_residual_quantitative),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_1),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_2),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_3),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_4),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_5),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_6),
    (`ZhangLS.Spec.ActualGramUniformBudget, `ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_7),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformExponent),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformFirstBoundaryConstant),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformFirstBoundaryConstant._proof_1),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformFirstBoundaryConstant._proof_2),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformMainConstant),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformMainConstant._proof_1),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformSecondBoundaryConstant),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_1),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_2),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_3),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_4),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_first_boundary_bound),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_first_boundary_constant_pos),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_main_constant_pos),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_pi_bound),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_scale_bounds),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_second_boundary_bound),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_second_boundary_bound._proof_1_1),
    (`ZhangLS.Spec.ActualGramUniformEnvelopes, `ZhangLS.Spec.actualGramUniform_second_boundary_constant_pos),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniformPairs),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_harmonic_bound),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_harmonic_bound._proof_1_1),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_pair_geometry),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_pairs_subset),
    (`ZhangLS.Spec.ActualGramUniformGeometry, `ZhangLS.Spec.actualGramUniform_support_ceiling),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniformArithmeticResidual.eq_1),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._proof_1_1),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_2),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_3),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_4),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_5),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_6),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_7),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_budget_square._simp_1_8),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_logT_tenth),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_residual_little_o),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_1),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_2),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_3),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_4),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_5),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_6),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_7),
    (`ZhangLS.Spec.ActualGramUniformLittleO, `ZhangLS.Spec.actualGramUniform_smooth_residual_little_o),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformFirstError),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformFirstNorm),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformSecondError),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformSecondError._proof_1),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformSecondError._proof_2),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniformSecondMain),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_envelopes_nonneg),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._proof_1_1),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_3),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_4),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_5),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_6),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_7),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_8),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_9),
    (`ZhangLS.Spec.ActualGramUniformSubstitution, `ZhangLS.Spec.lemma81Cutoff.eq_1)
  ]
  let expectedTypes : Array (Name × UInt64 × String) := #[
    (`ZhangLS.Spec.ActualGramUniformProfileData, 12841156711311012099, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.C, 14079045891415703397, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData._sizeOf_1, 9350184443552695944, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData._sizeOf_inst, 15661995099495484492, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.b, 14079045891415703397, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.casesOn, 13438099207049017785, "[`u]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.ctorIdx, 4514393626268531590, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.f, 12064810103601772215, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.f', 12064810103601772215, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.f'', 12064810103601772215, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.g, 12064810103601772215, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.g', 12064810103601772215, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.g'', 12064810103601772215, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hC, 15339587988872299350, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hb, 16761056036667977435, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hb0, 450079357339739159, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hf, 7800760812086336940, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hf', 15019282693927535937, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hf'', 17256764195246517771, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hf0, 6969686504510928489, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hfd, 16622220415862260896, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hfp0, 2703171340173829720, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hfpz, 7715964249776879670, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hft, 4652903311606842751, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hfz, 10334955908911550626, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hg, 16680160734971580549, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hg', 3359593385634943964, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hg'', 14519404926179608543, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hg0, 9647368704730086076, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hg1, 406893340645982617, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hgd, 16508317828829935359, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hgt, 5831526519160230471, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.hgz, 6719122737305530299, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.mk, 16642864549755733349, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.mk._flat_ctor, 16642864549755733349, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.mk.inj, 7160641457812657418, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.mk.injEq, 16886893986538687588, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.mk.noConfusion, 17358783343835347210, "[`u]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.mk.sizeOf_spec, 8294840432404176100, "[]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.noConfusion, 14823594414490240466, "[`u]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.noConfusionType, 6411699511209308277, "[`u]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.rec, 10954208164074596128, "[`u]"),
    (`ZhangLS.Spec.ActualGramUniformProfileData.recOn, 13438099207049017785, "[`u]"),
    (`ZhangLS.Spec.actualGramProfileProductResidual.eq_1, 1555847081160220288, "[]"),
    (`ZhangLS.Spec.actualGramUniformArithmeticResidual, 1273141720847297761, "[]"),
    (`ZhangLS.Spec.actualGramUniformPairs.eq_1, 12672646538243051561, "[]"),
    (`ZhangLS.Spec.actualGramUniform_assembled_error, 9076799466125309393, "[]"),
    (`ZhangLS.Spec.actualGramUniform_assembled_error._proof_1_1, 11249409692572316010, "[]"),
    (`ZhangLS.Spec.actualGramUniform_smooth_data, 2302192977803779053, "[]"),
    (`ZhangLS.Spec.actualGramUniformResidualConstant, 12013966826659514598, "[]"),
    (`ZhangLS.Spec.actualGramUniformResidualConstant._proof_1, 8609675347731722958, "[]"),
    (`ZhangLS.Spec.actualGramUniformResidualConstant._proof_2, 11184229512403634637, "[]"),
    (`ZhangLS.Spec.actualGramUniformWeightConstant, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.actualGramUniformWeightConstant._proof_1, 2729067472799564557, "[]"),
    (`ZhangLS.Spec.actualGramUniformWeightConstant._proof_2, 14647379146910394343, "[]"),
    (`ZhangLS.Spec.actualGramUniform_decay_comparison, 6382864894726521258, "[]"),
    (`ZhangLS.Spec.actualGramUniform_decay_comparison._proof_1_1, 9854210268353059402, "[]"),
    (`ZhangLS.Spec.actualGramUniform_decay_comparison._proof_1_2, 9465778536791259408, "[]"),
    (`ZhangLS.Spec.actualGramUniform_decay_comparison._proof_1_3, 316161574008607325, "[]"),
    (`ZhangLS.Spec.actualGramUniform_four_term_comparison, 11988466826703090681, "[]"),
    (`ZhangLS.Spec.actualGramUniform_residual_constant_nonneg, 16775277644149254571, "[]"),
    (`ZhangLS.Spec.actualGramUniform_residual_quantitative, 8065883623817964392, "[]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget, 12729080928610396531, "[]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGramUniform_weighted_budget._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniformExponent, 7337748955408223552, "[]"),
    (`ZhangLS.Spec.actualGramUniformFirstBoundaryConstant, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.actualGramUniformFirstBoundaryConstant._proof_1, 14647379146910394343, "[]"),
    (`ZhangLS.Spec.actualGramUniformFirstBoundaryConstant._proof_2, 6075289956554004985, "[]"),
    (`ZhangLS.Spec.actualGramUniformMainConstant, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.actualGramUniformMainConstant._proof_1, 772565646570335038, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondBoundaryConstant, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_1, 8609675347731722958, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_2, 5185406405428909789, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_3, 3457767388364009917, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondBoundaryConstant._proof_4, 420410228022065358, "[]"),
    (`ZhangLS.Spec.actualGramUniform_first_boundary_bound, 13181653615863950299, "[]"),
    (`ZhangLS.Spec.actualGramUniform_first_boundary_constant_pos, 16061783107593327913, "[]"),
    (`ZhangLS.Spec.actualGramUniform_main_constant_pos, 2626490382861778039, "[]"),
    (`ZhangLS.Spec.actualGramUniform_pi_bound, 16948116467217167050, "[]"),
    (`ZhangLS.Spec.actualGramUniform_scale_bounds, 7479488920376706253, "[]"),
    (`ZhangLS.Spec.actualGramUniform_second_boundary_bound, 13442277156251150726, "[]"),
    (`ZhangLS.Spec.actualGramUniform_second_boundary_bound._proof_1_1, 5708421964259984632, "[]"),
    (`ZhangLS.Spec.actualGramUniform_second_boundary_constant_pos, 1287710894087170572, "[]"),
    (`ZhangLS.Spec.actualGramUniformPairs, 6195479031539198252, "[]"),
    (`ZhangLS.Spec.actualGramUniform_harmonic_bound, 12853684739883111525, "[]"),
    (`ZhangLS.Spec.actualGramUniform_harmonic_bound._proof_1_1, 1193932418806536131, "[]"),
    (`ZhangLS.Spec.actualGramUniform_pair_geometry, 3410851082898285739, "[]"),
    (`ZhangLS.Spec.actualGramUniform_pairs_subset, 1491687726342824254, "[]"),
    (`ZhangLS.Spec.actualGramUniform_support_ceiling, 8662086794420307296, "[]"),
    (`ZhangLS.Spec.actualGramUniformArithmeticResidual.eq_1, 10130740128908295363, "[]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square, 7134915610981516112, "[]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._proof_1_1, 5749348782584039092, "[]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_2, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_3, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_4, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_5, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_6, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_7, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGramUniform_budget_square._simp_1_8, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_logT_tenth, 8169741476031059802, "[]"),
    (`ZhangLS.Spec.actualGramUniform_residual_little_o, 16340923419980295111, "[]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o, 235048669582874094, "[]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGramUniform_scalar_little_o._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_smooth_residual_little_o, 9141077160206003489, "[]"),
    (`ZhangLS.Spec.actualGramUniformFirstError, 12566617123724634169, "[]"),
    (`ZhangLS.Spec.actualGramUniformFirstNorm, 12566617123724634169, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondError, 12566617123724634169, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondError._proof_1, 2354442838308598510, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondError._proof_2, 11184229512403634637, "[]"),
    (`ZhangLS.Spec.actualGramUniformSecondMain, 12566617123724634169, "[]"),
    (`ZhangLS.Spec.actualGramUniform_envelopes_nonneg, 15765234635088237674, "[]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds, 6264244343488783369, "[]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._proof_1_1, 12354092655306101117, "[]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_3, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_4, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_5, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_6, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_7, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_8, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGramUniform_four_bounds._simp_1_9, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.lemma81Cutoff.eq_1, 17243639675844595419, "[]")
  ]
  let mut seen : Array (Name × Name) := #[]
  for (name, ci) in env.constants do
    if let some idx := env.getModuleIdxFor? name then
      let owner := moduleNames[idx]!
      if owners.contains owner then
        if seen.contains (owner,name) then
          throwError "Duplicate module-owned declaration {name}"
        if ci.isAxiom then throwError "Owned axiom {name}"
        let axs ← collectAxioms name
        unless axs.all (fun a => a == ``propext || a == ``Classical.choice || a == ``Quot.sound) do
          throwError "Nonstandard transitive axiom at {name}: {axs}"
        let typePretty ← liftTermElabM <| Meta.ppExpr ci.type
        unless expectedOwned.contains (owner,name) do
          throwError "Unexpected defining-module/name pair {owner} {name}"
        let some (_, pinnedType, pinnedUniverses) := expectedTypes.find? (fun p => p.1 == name)
          | throwError "Missing type pin {name}"
        unless hash typePretty.pretty == pinnedType do
          throwError "Full elaborated type fingerprint drift {name}"
        unless reprStr ci.levelParams == pinnedUniverses do
          throwError "Universe parameter drift {name}"
        let row := Json.mkObj [
          ("owner", toJson owner.toString),
          ("name", toJson name.toString),
          ("public", toJson (expectedPublic.contains (owner,name))),
          ("type_repr", toJson (reprStr ci.type)),
          ("type_lean_hash64", toJson (toString (hash typePretty.pretty))),
          ("type_pretty", toJson typePretty.pretty),
          ("universe_parameters_repr", toJson (reprStr ci.levelParams)),
          ("axioms", toJson (axs.map Name.toString)),
          ("used_constants", toJson (ci.getUsedConstantsAsSet.toArray.map Name.toString))]
        out.putStrLn s!"DECLARATION_JSON {row.compress}"
        out.flush
        seen := seen.push (owner,name)
  unless seen.size == 133 do
    throwError "Owned declaration count drift: {seen.size}"
  for pair in expectedPublic do
    unless seen.contains pair do
      throwError "Missing explicit declaration {pair.2}"
  unless expectedOwned.size == 133 && expectedTypes.size == 133 && expectedPublic.size == 38 do
    throwError "Incorrect pinned manifest counts"
  for pair in expectedOwned do
    unless seen.contains pair do
      throwError "Missing owned declaration {pair.2}"
  for owner in owners do
    let actual := (seen.filter (fun p => p.1 == owner)).size
    out.putStrLn s!"OWNER_COUNT {owner} {actual}"
  for mod in moduleNames do
    out.putStrLn s!"LOADED_MODULE {mod}"
  out.putStrLn s!"OWNERSHIP_TYPE_AXIOM_PASS {seen.size} PUBLIC {expectedPublic.size}"
  out.flush
