import ZhangLS.Spec.RoughCollisionRegressions
#print axioms ZhangLS.Spec.roughCollision_twist_multiplicative
#print axioms ZhangLS.Spec.roughCollision_rho_multiplicative
#print axioms ZhangLS.Spec.roughCollision_rho_tau_bound
#print axioms ZhangLS.Spec.roughCollision_rho_defect
#print axioms ZhangLS.Spec.roughCollision_common_prime_lower
#print axioms ZhangLS.Spec.roughCollision_multiple_subset
#print axioms ZhangLS.Spec.roughCollision_multiple_harmonic_bound
#print axioms ZhangLS.Spec.roughCollision_tau_prime
#print axioms ZhangLS.Spec.roughCollision_prime_multiple_bound
#print axioms ZhangLS.Spec.roughCollisionPrimes
#print axioms ZhangLS.Spec.roughCollision_prime_cover
#print axioms ZhangLS.Spec.roughCollision_prime_square_tail
#print axioms ZhangLS.Spec.roughCollision_tau_mass
#print axioms ZhangLS.Spec.roughCollisionDomain
#print axioms ZhangLS.Spec.roughCollision_weighted_defect_bound
#print axioms ZhangLS.Spec.roughCollision_kernel_factorization
#print axioms ZhangLS.Spec.roughCollision_actual_source_kernels
#print axioms ZhangLS.Spec.roughCollisionUniformBudget
#print axioms ZhangLS.Spec.roughCollisionNormalizedConstant
#print axioms ZhangLS.Spec.roughCollision_harmonic_budget
#print axioms ZhangLS.Spec.roughCollision_normalized_budget
#print axioms ZhangLS.Spec.roughCollision_budget_isLittleO_alpha
#print axioms ZhangLS.Spec.roughCollision_actual_source_uniform
#print axioms ZhangLS.Spec.roughCollision_supported_coprime
#print axioms ZhangLS.Spec.roughCollision_actual_B_smooth_split
#print axioms ZhangLS.Spec.roughCollisionSourceDefect
#print axioms ZhangLS.Spec.roughCollision_source_divisor_sum
#print axioms ZhangLS.Spec.roughCollision_source_character_divisor_sum
#print axioms ZhangLS.Spec.roughCollision_rho_prime_exact
#print axioms ZhangLS.Spec.roughCollision_rho_prime_square_exact
#print axioms ZhangLS.Spec.roughCollision_prime_collision_identity
#print axioms ZhangLS.Spec.roughCollision_H14_boundary
#print axioms ZhangLS.Spec.roughCollision_literal_B3_zero
#print axioms ZhangLS.Spec.roughCollision_U_expanded
#print axioms ZhangLS.Spec.roughCollision_V_expanded
#print axioms ZhangLS.Spec.roughCollision_rough_domain_expanded
#print axioms ZhangLS.Spec.roughCollision_small_prime_excluded
#print axioms ZhangLS.Spec.roughCollision_constant_expanded
#print axioms ZhangLS.Spec.roughCollision_supported_one
#print axioms ZhangLS.Spec.roughCollision_rhostar_is_actual_nu
