import ZhangLS.Spec.ActualGramMovingErrorIntegral
import ZhangLS.Spec.ActualGramFirstProfileError
import ZhangLS.Spec.ActualGramSecondProfileError
import ZhangLS.Spec.ActualGramBoxAttachment
import ZhangLS.Spec.ActualGramSmoothProfileBinding
import ZhangLS.Spec.ActualGramWeightedProfileAssembly
import ZhangLS.Spec.ActualGramPiCollapse
import ZhangLS.Spec.ActualGramArithmeticAttachment
import ZhangLS.Spec.ActualGramRamp
import ZhangLS.Spec.ActualGramClosedWeightLayer
import ZhangLS.Spec.ActualGramFiniteSuperposition
import ZhangLS.Spec.ActualGramLogKernelBridge
import ZhangLS.Spec.ActualGramOriginalScaling
import ZhangLS.Spec.ActualGramOneSidedSuperposition
import ZhangLS.Spec.ActualGramMainKernelBridge
import ZhangLS.Spec.ActualGramSmoothingBounds
set_option autoImplicit false
set_option maxHeartbeats 24000000
set_option pp.all true
set_option pp.maxSteps 10000000
set_option pp.universes true
/-!
Focused ownership/type/axiom audit for the sixteen actual Gram profile modules.
Pins every one of the 154 owned declarations, including all generated helpers;
92 are source-public, with 44 owned / 29 public contributed by the six restored
integral/profile modules. Every full elaborated type is fingerprinted as the complete pp.all rendering
under fixed options; universe parameter lists are pinned by exact equality.
The executable type fingerprint is Lean's deterministic 64-bit String hash,
which has a collision risk and is not a proof of full-string type equality.
Separate per-type SHA256s for both complete renderings and raw expression trees
are recorded in the evidence manifest; the audit prints both for reproduction.
A separate fresh private audit also checked exact full-string type equality.
No additional theorem, fixed-H norm completion, or common substitution is asserted.
Run from the repository root: lake env lean -j1 -M6144 audit/CloudGramProfileInventory.lean
-/
open Lean Elab Command in
run_cmd do
  let env ← getEnv
  let moduleNames := env.header.moduleNames
  let owners : Array Name := #[`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.ActualGramClosedWeightLayer, `ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.ActualGramOneSidedSuperposition, `ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.ActualGramSecondProfileError, `ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.ActualGramWeightedProfileAssembly]
  let expectedOwned : Array (Name × Name) := #[
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramFirst),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramFirst.eq_1),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramProfileSequence),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramProfileSequence.eq_1),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramSecond),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramSecond.eq_1),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_P7_profile_factorization),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_P7_profile_factorization._simp_1_4),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_character_mul),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_character_square),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_finite_main_attachment),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_profile_conjugate),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_1),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_2),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_3),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_4),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_5),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_6),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_7),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_8),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_P7_box_main_attachment),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_original_box_fiber),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_original_box_fiber._proof_1_4),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_original_box_fiber._simp_1_1),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_original_box_fiber._simp_1_2),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_original_box_fiber._simp_1_3),
    (`ZhangLS.Spec.ActualGramClosedWeightLayer, `ZhangLS.Spec.actualGram_actual_weight_closed_layer),
    (`ZhangLS.Spec.ActualGramClosedWeightLayer, `ZhangLS.Spec.actualGram_weight_product_endpoint),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGramClippedRamp),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGramClippedRamp.eq_1),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_clipped_ramp_continuous),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_clipped_ramp_of_ge),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_clipped_ramp_of_le),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_finite_ramp_superposition),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_fixed_interval_ramp),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_ramp_density_continuous),
    (`ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.actualGram_first_profile_error_uniform),
    (`ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.actualGram_first_profile_error_uniform._proof_1_1),
    (`ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.actualGram_first_profile_norm_uniform),
    (`ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.actualGram_first_profile_norm_uniform._proof_1_1),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGramLogSmoothedSum),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_clipped_sum_eq_smoothed),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_clipped_sum_eq_smoothed._simp_1_1),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_first_smoothed_superposition),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_kernel_first),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_kernel_second),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothed_superposition),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_1),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_2),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_3),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_4),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_5),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_6),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_7),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_second_smoothed_superposition),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_smoothing_cutoff_inside_original),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_first_main_kernel),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_first_main_superposition),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_1),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_2),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_3),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_4),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_5),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_6),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_7),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_mu6_nonzero),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_positive_cutoff_cpow),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_second_main_kernel),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_second_main_superposition),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_volterra_terminal_extension),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_log_smoothed_continuousOn),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_log_smoothed_continuousOn._simp_1_1),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_moving_layer_integral_bound),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_scaled_moving_layer_bound),
    (`ZhangLS.Spec.ActualGramOneSidedSuperposition, `ZhangLS.Spec.actualGram_log_superposition_from_product),
    (`ZhangLS.Spec.ActualGramOneSidedSuperposition, `ZhangLS.Spec.actualGram_ramp_above_left_endpoint),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_log_moving_band),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_exp_power),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_log_scale),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_log_scale_pos),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_moving_T_band),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_negative_scaled),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_2),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_3),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_4),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_5),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_6),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_7),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_8),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.lemma82SmoothingBeta.eq_1),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_character_prime_denominator),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_local_pi_collapse),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_pi_divisor_collapse),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_squarefree_divisor_expansion),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_squarefree_divisor_expansion._simp_1_1),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_squarefree_divisor_expansion._simp_1_2),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_totient_prime_product),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_totient_ratio_product),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.lemma83Pi.eq_1),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGramRampDensity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGramRampDensity._proof_1),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGramRampDensity.eq_1),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_density_integral),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_exponential_antiderivative),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_exponential_identity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_first_main_identity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_ramp_antiderivative),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_ramp_identity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_second_main_identity),
    (`ZhangLS.Spec.ActualGramSecondProfileError, `ZhangLS.Spec.actualGram_second_profile_error_uniform),
    (`ZhangLS.Spec.ActualGramSecondProfileError, `ZhangLS.Spec.actualGram_second_profile_error_uniform._proof_1_1),
    (`ZhangLS.Spec.ActualGramSecondProfileError, `ZhangLS.Spec.actualGram_second_profile_main_norm),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_density_bound),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_derivatives),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_global_bound),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_global_bound._simp_1_1),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_global_bound._simp_1_2),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_global_bound._simp_1_3),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_traces),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_zero_on_closed_exterior),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramFirstBoundaryBudget),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramFirstBoundaryBudget._proof_1),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramFirstBoundaryBudget._proof_2),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramSecondBoundaryBudget),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramSecondBoundaryBudget._proof_1),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramSecondBoundaryBudget._proof_2),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramSecondBoundaryBudget._proof_3),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_first_small_error),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_second_small_error),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_smoothing_errors_uniform),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_smoothing_errors_uniform._proof_1_1),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramDifferentialFirst),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramDifferentialFirst.eq_1),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramDifferentialSecond),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramDifferentialSecond._proof_1),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramFiniteProfileKernel),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramFiniteProfileKernel.eq_1),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramFirstProfileMain),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramFirstProfileMain.eq_1),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramProfileProductResidual),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramSecondProfileMain),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_P7_main_error_identity),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_P7_main_error_supported),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_finite_profile_kernel_strict_support),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_first_profile_main_zero_past),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_first_zero_past_profile),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_profile_inner_cutoffs),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_profile_product_residual_zero),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_profile_residual_restrict),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_weighted_profile_error_bound)
  ]
  let expectedPublic : Array (Name × Name) := #[
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramFirst),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramProfileSequence),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGramSecond),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_P7_profile_factorization),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_character_mul),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_character_square),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_finite_main_attachment),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_profile_conjugate),
    (`ZhangLS.Spec.ActualGramArithmeticAttachment, `ZhangLS.Spec.actualGram_weight_pi_collapse),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_P7_box_main_attachment),
    (`ZhangLS.Spec.ActualGramBoxAttachment, `ZhangLS.Spec.actualGram_original_box_fiber),
    (`ZhangLS.Spec.ActualGramClosedWeightLayer, `ZhangLS.Spec.actualGram_actual_weight_closed_layer),
    (`ZhangLS.Spec.ActualGramClosedWeightLayer, `ZhangLS.Spec.actualGram_weight_product_endpoint),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGramClippedRamp),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_clipped_ramp_continuous),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_clipped_ramp_of_ge),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_clipped_ramp_of_le),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_finite_ramp_superposition),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_fixed_interval_ramp),
    (`ZhangLS.Spec.ActualGramFiniteSuperposition, `ZhangLS.Spec.actualGram_ramp_density_continuous),
    (`ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.actualGram_first_profile_error_uniform),
    (`ZhangLS.Spec.ActualGramFirstProfileError, `ZhangLS.Spec.actualGram_first_profile_norm_uniform),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGramLogSmoothedSum),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_clipped_sum_eq_smoothed),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_first_smoothed_superposition),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_kernel_first),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_kernel_second),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothed_superposition),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_log_smoothing_term),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_second_smoothed_superposition),
    (`ZhangLS.Spec.ActualGramLogKernelBridge, `ZhangLS.Spec.actualGram_smoothing_cutoff_inside_original),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_first_main_kernel),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_first_main_superposition),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_log_ratio_scale),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_mu6_nonzero),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_positive_cutoff_cpow),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_second_main_kernel),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_second_main_superposition),
    (`ZhangLS.Spec.ActualGramMainKernelBridge, `ZhangLS.Spec.actualGram_volterra_terminal_extension),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_log_smoothed_continuousOn),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_moving_layer_integral_bound),
    (`ZhangLS.Spec.ActualGramMovingErrorIntegral, `ZhangLS.Spec.actualGram_scaled_moving_layer_bound),
    (`ZhangLS.Spec.ActualGramOneSidedSuperposition, `ZhangLS.Spec.actualGram_log_superposition_from_product),
    (`ZhangLS.Spec.ActualGramOneSidedSuperposition, `ZhangLS.Spec.actualGram_ramp_above_left_endpoint),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_log_moving_band),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_exp_power),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_log_scale),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_log_scale_pos),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_moving_T_band),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_negative_scaled),
    (`ZhangLS.Spec.ActualGramOriginalScaling, `ZhangLS.Spec.actualGram_original_mu6_scaled),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_character_prime_denominator),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_local_pi_collapse),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_pi_divisor_collapse),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_squarefree_divisor_expansion),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_totient_prime_product),
    (`ZhangLS.Spec.ActualGramPiCollapse, `ZhangLS.Spec.actualGram_totient_ratio_product),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGramRampDensity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_density_integral),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_exponential_antiderivative),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_exponential_identity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_first_main_identity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_ramp_antiderivative),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_ramp_identity),
    (`ZhangLS.Spec.ActualGramRamp, `ZhangLS.Spec.actualGram_second_main_identity),
    (`ZhangLS.Spec.ActualGramSecondProfileError, `ZhangLS.Spec.actualGram_second_profile_error_uniform),
    (`ZhangLS.Spec.ActualGramSecondProfileError, `ZhangLS.Spec.actualGram_second_profile_main_norm),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_density_bound),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_derivatives),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_global_bound),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_smooth_profile_traces),
    (`ZhangLS.Spec.ActualGramSmoothProfileBinding, `ZhangLS.Spec.actualGram_zero_on_closed_exterior),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramFirstBoundaryBudget),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGramSecondBoundaryBudget),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_first_small_error),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_second_small_error),
    (`ZhangLS.Spec.ActualGramSmoothingBounds, `ZhangLS.Spec.actualGram_smoothing_errors_uniform),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramDifferentialFirst),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramDifferentialSecond),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramFiniteProfileKernel),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramFirstProfileMain),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramProfileProductResidual),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGramSecondProfileMain),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_P7_main_error_identity),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_P7_main_error_supported),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_finite_profile_kernel_strict_support),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_first_profile_main_zero_past),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_first_zero_past_profile),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_profile_inner_cutoffs),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_profile_product_residual_zero),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_profile_residual_restrict),
    (`ZhangLS.Spec.ActualGramWeightedProfileAssembly, `ZhangLS.Spec.actualGram_weighted_profile_error_bound)
  ]
  let expectedTypes : Array (Name × UInt64 × String) := #[
    (`ZhangLS.Spec.actualGramFirst, 15021856891931998856, "[]"),
    (`ZhangLS.Spec.actualGramFirst.eq_1, 11873596469471815654, "[]"),
    (`ZhangLS.Spec.actualGramProfileSequence, 12731836572808338987, "[]"),
    (`ZhangLS.Spec.actualGramProfileSequence.eq_1, 8786050005601842596, "[]"),
    (`ZhangLS.Spec.actualGramSecond, 11170374606741078242, "[]"),
    (`ZhangLS.Spec.actualGramSecond.eq_1, 8354613568782133273, "[]"),
    (`ZhangLS.Spec.actualGram_P7_profile_factorization, 16194579307783063697, "[]"),
    (`ZhangLS.Spec.actualGram_P7_profile_factorization._simp_1_4, 2608467155204133230, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_character_mul, 18382711194044312343, "[]"),
    (`ZhangLS.Spec.actualGram_character_square, 3739313607841462726, "[]"),
    (`ZhangLS.Spec.actualGram_finite_main_attachment, 3515201462810351846, "[]"),
    (`ZhangLS.Spec.actualGram_profile_conjugate, 7947713663825397572, "[]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse, 16150378564257930082, "[]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_1, 2608467155204133230, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_2, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_3, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_4, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_5, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_6, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_7, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGram_weight_pi_collapse._simp_1_8, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_P7_box_main_attachment, 11120844591872955552, "[]"),
    (`ZhangLS.Spec.actualGram_original_box_fiber, 4158593083152525925, "[]"),
    (`ZhangLS.Spec.actualGram_original_box_fiber._proof_1_4, 12106918212266575667, "[]"),
    (`ZhangLS.Spec.actualGram_original_box_fiber._simp_1_1, 1988649516832762782, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_original_box_fiber._simp_1_2, 13318128363268500191, "[`u_1, `u_2]"),
    (`ZhangLS.Spec.actualGram_original_box_fiber._simp_1_3, 2821273606286481332, "[]"),
    (`ZhangLS.Spec.actualGram_actual_weight_closed_layer, 4553221081616544320, "[]"),
    (`ZhangLS.Spec.actualGram_weight_product_endpoint, 2763220643751271938, "[]"),
    (`ZhangLS.Spec.actualGramClippedRamp, 12620217478735857625, "[]"),
    (`ZhangLS.Spec.actualGramClippedRamp.eq_1, 3869110794234743245, "[]"),
    (`ZhangLS.Spec.actualGram_clipped_ramp_continuous, 7489626713884929446, "[]"),
    (`ZhangLS.Spec.actualGram_clipped_ramp_of_ge, 1917942177523970360, "[]"),
    (`ZhangLS.Spec.actualGram_clipped_ramp_of_le, 780585936363713155, "[]"),
    (`ZhangLS.Spec.actualGram_finite_ramp_superposition, 1548862692948365895, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_fixed_interval_ramp, 17634487069465321324, "[]"),
    (`ZhangLS.Spec.actualGram_ramp_density_continuous, 7750173957417014840, "[]"),
    (`ZhangLS.Spec.actualGram_first_profile_error_uniform, 10513283733326208573, "[]"),
    (`ZhangLS.Spec.actualGram_first_profile_error_uniform._proof_1_1, 7175321828073770338, "[]"),
    (`ZhangLS.Spec.actualGram_first_profile_norm_uniform, 2627870339855472296, "[]"),
    (`ZhangLS.Spec.actualGram_first_profile_norm_uniform._proof_1_1, 14169154628881598620, "[]"),
    (`ZhangLS.Spec.actualGramLogSmoothedSum, 16218191610518668346, "[]"),
    (`ZhangLS.Spec.actualGram_clipped_sum_eq_smoothed, 600462789141497722, "[]"),
    (`ZhangLS.Spec.actualGram_clipped_sum_eq_smoothed._simp_1_1, 4425616438191903068, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_first_smoothed_superposition, 17715099055340174446, "[]"),
    (`ZhangLS.Spec.actualGram_log_kernel_first, 1923845462482203329, "[]"),
    (`ZhangLS.Spec.actualGram_log_kernel_second, 5520853467409920105, "[]"),
    (`ZhangLS.Spec.actualGram_log_smoothed_superposition, 15186730668128894320, "[]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term, 18179273793410439863, "[]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGram_log_smoothing_term._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_second_smoothed_superposition, 9770632627601664746, "[]"),
    (`ZhangLS.Spec.actualGram_smoothing_cutoff_inside_original, 15686239964626361127, "[]"),
    (`ZhangLS.Spec.actualGram_first_main_kernel, 5115587870073370831, "[]"),
    (`ZhangLS.Spec.actualGram_first_main_superposition, 4516510028963630661, "[]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale, 9834988961350812107, "[]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGram_log_ratio_scale._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_mu6_nonzero, 14288216535891912326, "[]"),
    (`ZhangLS.Spec.actualGram_positive_cutoff_cpow, 14203548057679516773, "[]"),
    (`ZhangLS.Spec.actualGram_second_main_kernel, 13345793555895348057, "[]"),
    (`ZhangLS.Spec.actualGram_second_main_superposition, 3425664375003530301, "[]"),
    (`ZhangLS.Spec.actualGram_volterra_terminal_extension, 7114889615665709299, "[]"),
    (`ZhangLS.Spec.actualGram_log_smoothed_continuousOn, 14704925810942748494, "[]"),
    (`ZhangLS.Spec.actualGram_log_smoothed_continuousOn._simp_1_1, 4425616438191903068, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_moving_layer_integral_bound, 1066364894812907507, "[]"),
    (`ZhangLS.Spec.actualGram_scaled_moving_layer_bound, 14874368406601696801, "[]"),
    (`ZhangLS.Spec.actualGram_log_superposition_from_product, 2142355595458813003, "[]"),
    (`ZhangLS.Spec.actualGram_ramp_above_left_endpoint, 14949962037448831170, "[]"),
    (`ZhangLS.Spec.actualGram_log_moving_band, 1736777494827091120, "[]"),
    (`ZhangLS.Spec.actualGram_original_exp_power, 6602736626200119886, "[]"),
    (`ZhangLS.Spec.actualGram_original_log_scale, 11370915016529772675, "[]"),
    (`ZhangLS.Spec.actualGram_original_log_scale_pos, 1778252500268084488, "[]"),
    (`ZhangLS.Spec.actualGram_original_moving_T_band, 4102268060112114566, "[]"),
    (`ZhangLS.Spec.actualGram_original_mu6_negative_scaled, 5183327280967719783, "[]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled, 4642322575033151510, "[]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_2, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_3, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_4, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_5, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_6, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_7, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.actualGram_original_mu6_scaled._simp_1_8, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.lemma82SmoothingBeta.eq_1, 8302112211297439384, "[]"),
    (`ZhangLS.Spec.actualGram_character_prime_denominator, 8173147098384764212, "[]"),
    (`ZhangLS.Spec.actualGram_local_pi_collapse, 5826276064369110550, "[]"),
    (`ZhangLS.Spec.actualGram_pi_divisor_collapse, 8049371927946344455, "[]"),
    (`ZhangLS.Spec.actualGram_squarefree_divisor_expansion, 10868199973104203631, "[]"),
    (`ZhangLS.Spec.actualGram_squarefree_divisor_expansion._simp_1_1, 1988649516832762782, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_squarefree_divisor_expansion._simp_1_2, 8438004994277470691, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_totient_prime_product, 8040018395585021134, "[]"),
    (`ZhangLS.Spec.actualGram_totient_ratio_product, 5248149694665703920, "[]"),
    (`ZhangLS.Spec.lemma83Pi.eq_1, 16778953811242269646, "[]"),
    (`ZhangLS.Spec.actualGramRampDensity, 13225431690422163216, "[]"),
    (`ZhangLS.Spec.actualGramRampDensity._proof_1, 14647379146910394343, "[]"),
    (`ZhangLS.Spec.actualGramRampDensity.eq_1, 4796173668995771263, "[]"),
    (`ZhangLS.Spec.actualGram_density_integral, 8592868610267505595, "[]"),
    (`ZhangLS.Spec.actualGram_exponential_antiderivative, 9467482351168398187, "[]"),
    (`ZhangLS.Spec.actualGram_exponential_identity, 2776453464957822031, "[]"),
    (`ZhangLS.Spec.actualGram_first_main_identity, 4756705168326353959, "[]"),
    (`ZhangLS.Spec.actualGram_ramp_antiderivative, 5563459967041892073, "[]"),
    (`ZhangLS.Spec.actualGram_ramp_identity, 13439656056271712450, "[]"),
    (`ZhangLS.Spec.actualGram_second_main_identity, 12218864587130543994, "[]"),
    (`ZhangLS.Spec.actualGram_second_profile_error_uniform, 2123093942681103854, "[]"),
    (`ZhangLS.Spec.actualGram_second_profile_error_uniform._proof_1_1, 8805387222783395551, "[]"),
    (`ZhangLS.Spec.actualGram_second_profile_main_norm, 1798956792887464665, "[]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_density_bound, 8421635488125174059, "[]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_derivatives, 11673764970736701777, "[]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_global_bound, 2227627087012137250, "[]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_global_bound._simp_1_1, 12275696166154983271, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_global_bound._simp_1_2, 9896501609172849848, "[]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_global_bound._simp_1_3, 3038822788580438809, "[`u_1]"),
    (`ZhangLS.Spec.actualGram_smooth_profile_traces, 1532285372023456899, "[]"),
    (`ZhangLS.Spec.actualGram_zero_on_closed_exterior, 10084562443993060883, "[]"),
    (`ZhangLS.Spec.actualGramFirstBoundaryBudget, 12957806670630576245, "[]"),
    (`ZhangLS.Spec.actualGramFirstBoundaryBudget._proof_1, 5185406405428909789, "[]"),
    (`ZhangLS.Spec.actualGramFirstBoundaryBudget._proof_2, 6075289956554004985, "[]"),
    (`ZhangLS.Spec.actualGramSecondBoundaryBudget, 15075462274320329686, "[]"),
    (`ZhangLS.Spec.actualGramSecondBoundaryBudget._proof_1, 2354442838308598510, "[]"),
    (`ZhangLS.Spec.actualGramSecondBoundaryBudget._proof_2, 3457767388364009917, "[]"),
    (`ZhangLS.Spec.actualGramSecondBoundaryBudget._proof_3, 420410228022065358, "[]"),
    (`ZhangLS.Spec.actualGram_first_small_error, 10414857863939149620, "[]"),
    (`ZhangLS.Spec.actualGram_second_small_error, 9422562012746797839, "[]"),
    (`ZhangLS.Spec.actualGram_smoothing_errors_uniform, 10487894123758581809, "[]"),
    (`ZhangLS.Spec.actualGram_smoothing_errors_uniform._proof_1_1, 16673201377485100598, "[]"),
    (`ZhangLS.Spec.actualGramDifferentialFirst, 5623605483578776590, "[]"),
    (`ZhangLS.Spec.actualGramDifferentialFirst.eq_1, 12952566684432170765, "[]"),
    (`ZhangLS.Spec.actualGramDifferentialSecond, 13687049883206256124, "[]"),
    (`ZhangLS.Spec.actualGramDifferentialSecond._proof_1, 14568674335733737352, "[]"),
    (`ZhangLS.Spec.actualGramFiniteProfileKernel, 15783365939472505673, "[]"),
    (`ZhangLS.Spec.actualGramFiniteProfileKernel.eq_1, 10542566999244213276, "[]"),
    (`ZhangLS.Spec.actualGramFirstProfileMain, 12779824625919468686, "[]"),
    (`ZhangLS.Spec.actualGramFirstProfileMain.eq_1, 10158424297647718348, "[]"),
    (`ZhangLS.Spec.actualGramProfileProductResidual, 6987422880751958751, "[]"),
    (`ZhangLS.Spec.actualGramSecondProfileMain, 7452512050455456478, "[]"),
    (`ZhangLS.Spec.actualGram_P7_main_error_identity, 17626138159764103248, "[]"),
    (`ZhangLS.Spec.actualGram_P7_main_error_supported, 14733852598353193884, "[]"),
    (`ZhangLS.Spec.actualGram_finite_profile_kernel_strict_support, 5258550081627119990, "[]"),
    (`ZhangLS.Spec.actualGram_first_profile_main_zero_past, 12798041060576179895, "[]"),
    (`ZhangLS.Spec.actualGram_first_zero_past_profile, 7907358006910536602, "[]"),
    (`ZhangLS.Spec.actualGram_profile_inner_cutoffs, 13594674900885537106, "[]"),
    (`ZhangLS.Spec.actualGram_profile_product_residual_zero, 14397165803102091679, "[]"),
    (`ZhangLS.Spec.actualGram_profile_residual_restrict, 480589444185082195, "[]"),
    (`ZhangLS.Spec.actualGram_weighted_profile_error_bound, 8697371120009258137, "[]")
  ]
  let mut seen : Array (Name × Name) := #[]
  for (name, ci) in env.constants do
    if let some idx := env.getModuleIdxFor? name then
      let owner := moduleNames[idx]!
      if owners.contains owner then
        unless expectedOwned.contains (owner,name) do
          throwError "Unexpected owned declaration {owner} {name}"
        if seen.contains (owner,name) then
          throwError "Duplicate owned declaration {name}"
        let axs ← collectAxioms name
        unless axs.all (fun a => a == ``propext || a == ``Classical.choice || a == ``Quot.sound) do
          throwError "Nonstandard axiom at {name}: {axs}"
        let typePretty ← liftTermElabM <| Meta.ppExpr ci.type
        let some (_, pinnedType, pinnedUniverses) := expectedTypes.find? (fun p => p.1 == name)
          | throwError "Missing type pin {name}"
        unless hash typePretty.pretty == pinnedType do
          throwError "Full elaborated type fingerprint drift {name}"
        unless reprStr ci.levelParams == pinnedUniverses do
          throwError "Universe parameter drift {name}"
        let row := Json.mkObj [
          ("owner", toJson owner.toString),
          ("name", toJson name.toString),
          ("public", toJson (expectedPublic.contains (owner,name))),
          ("type_repr", toJson (reprStr ci.type)),
          ("type_lean_hash64", toJson (toString (hash typePretty.pretty))),
          ("type_pretty", toJson typePretty.pretty),
          ("universe_parameters_repr", toJson (reprStr ci.levelParams)),
          ("axioms", toJson (axs.map Name.toString)),
          ("used_constants", toJson (ci.getUsedConstantsAsSet.toArray.map Name.toString))]
        logInfo m!"DECLARATION_JSON {row.compress}"
        seen := seen.push (owner,name)
  unless seen.size == 154 && expectedOwned.size == 154 && expectedPublic.size == 92 && expectedTypes.size == 154 do
    throwError "Exact ownership/public count drift {seen.size}"
  for pair in expectedOwned do
    unless seen.contains pair do
      throwError "Missing owned declaration {pair.2}"
  for pair in expectedPublic do
    unless seen.contains pair do
      throwError "Missing public declaration {pair.2}"
  for mod in moduleNames do
    logInfo m!"LOADED_MODULE {mod}"
  logInfo m!"OWNERSHIP_TYPE_AXIOM_PASS {seen.size} PUBLIC {expectedPublic.size} FULL_TYPE_FINGERPRINTS {expectedTypes.size}"
