import ZhangLS.Spec.Lemma162ThinStripBound
import ZhangLS.Spec.Lemma162ExactCenter
import ZhangLS.Spec.Lemma162SectorBound
import ZhangLS.Spec.Lemma162CenterComparison
import ZhangLS.Spec.Lemma162CorrectedCenter
import ZhangLS.Spec.Lemma162CauchyBounds
import ZhangLS.Spec.Lemma162CorrectedQuantitative

#print axioms ZhangLS.Spec.lemma162UnramifiedProductBound
#print axioms ZhangLS.Spec.lemma162_unramified_product_bound_pos
#print axioms ZhangLS.Spec.lemma162_raw_euler_separated_bound
#print axioms ZhangLS.Spec.lemma162_corrected_strip_bound
#print axioms ZhangLS.Spec.lemma162ThinStripConstant
#print axioms ZhangLS.Spec.lemma162_thin_strip_constant_pos
#print axioms ZhangLS.Spec.lemma162_paper_thin_strip_bound
#print axioms ZhangLS.Spec.lemma162_raw_rational_center
#print axioms ZhangLS.Spec.lemma162_actual_raw_center
#print axioms ZhangLS.Spec.lemma162_actual_raw_center_zero
#print axioms ZhangLS.Spec.lemma162_actual_raw_center_diagonal
#print axioms ZhangLS.Spec.lemma162_actual_raw_product_center_diagonal
#print axioms ZhangLS.Spec.lemma162_ramified_sector_bound
#print axioms ZhangLS.Spec.lemma162_raw_sector_bound
#print axioms ZhangLS.Spec.lemma162SectorConstant
#print axioms ZhangLS.Spec.lemma162_sector_constant_pos
#print axioms ZhangLS.Spec.lemma162_paper_sector_bound
#print axioms ZhangLS.Spec.lemma162_disk_in_sector
#print axioms ZhangLS.Spec.lemma162_paper_disk_bound
#print axioms ZhangLS.Spec.lemma162_raw_center_prime_comparison
#print axioms ZhangLS.Spec.lemma162_raw_center_prime_norm
#print axioms ZhangLS.Spec.lemma162CenterProductBound
#print axioms ZhangLS.Spec.lemma162CenterVariationConstant
#print axioms ZhangLS.Spec.lemma162_center_product_bound_pos
#print axioms ZhangLS.Spec.lemma162_center_variation_constant_pos
#print axioms ZhangLS.Spec.lemma162_center_square_summable
#print axioms ZhangLS.Spec.lemma162_center_variation_summable
#print axioms ZhangLS.Spec.lemma162_finite_center_majorant_bound
#print axioms ZhangLS.Spec.lemma162_raw_center_product_comparison
#print axioms ZhangLS.Spec.lemma162_raw_center_zero_exact
#print axioms ZhangLS.Spec.lemma162_raw_center_zero_norm_le_one
#print axioms ZhangLS.Spec.lemma162CorrectedCenterMain
#print axioms ZhangLS.Spec.lemma162_corrected_center_main_eq
#print axioms ZhangLS.Spec.lemma162CorrectedCenterVariationConstant
#print axioms ZhangLS.Spec.lemma162_corrected_center_variation_constant_pos
#print axioms ZhangLS.Spec.lemma162_corrected_center_comparison
#print axioms ZhangLS.Spec.lemma162CorrectedCenterAlphaConstant
#print axioms ZhangLS.Spec.lemma162_corrected_center_alpha_constant_pos
#print axioms ZhangLS.Spec.lemma162_paper_corrected_center_alpha
#print axioms ZhangLS.Spec.lemma162_paper_corrected_center
#print axioms ZhangLS.Spec.lemma162_paper_cauchy_bounds
#print axioms ZhangLS.Spec.lemma162_paper_corrected_center_four
#print axioms ZhangLS.Spec.Lemma162CorrectedQuantitativeAt
#print axioms ZhangLS.Spec.lemma162_corrected_quantitative_proved
#print axioms ZhangLS.Spec.lemma162_corrected_quantitative_shared_constant
