import ZhangLS.Spec.BSourceRegressions

#print axioms ZhangLS.Spec.BStrictSupport
#print axioms ZhangLS.Spec.b_strict_support_mem
#print axioms ZhangLS.Spec.b_strict_support_term_zero
#print axioms ZhangLS.Spec.b_strict_support_summable
#print axioms ZhangLS.Spec.b_strict_support_LSeries_eq_polynomial
#print axioms ZhangLS.Spec.b_strict_support_mul_left
#print axioms ZhangLS.Spec.b_strict_support_add
#print axioms ZhangLS.Spec.b_strict_support_convolution
#print axioms ZhangLS.Spec.b_finite_polynomial_product
#print axioms ZhangLS.Spec.bH14Coefficient
#print axioms ZhangLS.Spec.b_kernel_strict_support
#print axioms ZhangLS.Spec.b_h14_strict_support
#print axioms ZhangLS.Spec.bFirstCutoff
#print axioms ZhangLS.Spec.bSecondCutoff
#print axioms ZhangLS.Spec.bProductCutoff
#print axioms ZhangLS.Spec.b_first_strict_support
#print axioms ZhangLS.Spec.b_second_strict_support
#print axioms ZhangLS.Spec.b_canonical_eq_convolution
#print axioms ZhangLS.Spec.b_canonical_strict_support
#print axioms ZhangLS.Spec.b_canonical_zero_at_or_above
#print axioms ZhangLS.Spec.b_psi_strict_support
#print axioms ZhangLS.Spec.bSourceH
#print axioms ZhangLS.Spec.bSourceH14
#print axioms ZhangLS.Spec.bSourceH12
#print axioms ZhangLS.Spec.bSourceH13
#print axioms ZhangLS.Spec.bSourceH2
#print axioms ZhangLS.Spec.bSourceB
#print axioms ZhangLS.Spec.b_source_H_eq_LSeries
#print axioms ZhangLS.Spec.b_kernel_cut_self
#print axioms ZhangLS.Spec.b_source_H14_eq_LSeries
#print axioms ZhangLS.Spec.b_source_H12_eq_LSeries
#print axioms ZhangLS.Spec.b_source_H13_eq_LSeries
#print axioms ZhangLS.Spec.b_LSeries_weighted_linear
#print axioms ZhangLS.Spec.b_source_first_eq_LSeries
#print axioms ZhangLS.Spec.b_source_second_eq_LSeries
#print axioms ZhangLS.Spec.b_twisted_product_coefficient
#print axioms ZhangLS.Spec.b_source_product_eq_chiPsi_series
#print axioms ZhangLS.Spec.b_source_product_eq_psi_series
#print axioms ZhangLS.Spec.b_source_product_eq_chiPsi_polynomial
#print axioms ZhangLS.Spec.b_source_product_eq_psi_polynomial
#print axioms ZhangLS.Spec.b_canonical_four_kernel_expansion
#print axioms ZhangLS.Spec.b_ramified_display_invariance
#print axioms ZhangLS.Spec.b_psi_ramified_zero
#print axioms ZhangLS.Spec.b_power_twist_term
#print axioms ZhangLS.Spec.b_power_twist_summable
#print axioms ZhangLS.Spec.b_power_twist_LSeries
#print axioms ZhangLS.Spec.b_twist_arithmetic_product
#print axioms ZhangLS.Spec.b_moebius_twist_summable
#print axioms ZhangLS.Spec.b_kappa_twist_summable
#print axioms ZhangLS.Spec.b_kappa_twist_LSeries_ratio
#print axioms ZhangLS.Spec.bPsiArithmetic
#print axioms ZhangLS.Spec.b_source_ratio_convolution
#print axioms ZhangLS.Spec.b_kernel_norm_le_one
#print axioms ZhangLS.Spec.b_beta6_re
#print axioms ZhangLS.Spec.b_beta7_re
#print axioms ZhangLS.Spec.b_h14_norm_le_one
#print axioms ZhangLS.Spec.b_first_norm_bound
#print axioms ZhangLS.Spec.b_second_norm_bound
#print axioms ZhangLS.Spec.bCoefficientConstant
#print axioms ZhangLS.Spec.b_coefficient_constant_nonneg
#print axioms ZhangLS.Spec.b_coefficient_constant_pos
#print axioms ZhangLS.Spec.b_arithmetic_convolution_majorant
#print axioms ZhangLS.Spec.bFirstArithmetic
#print axioms ZhangLS.Spec.bSecondArithmetic
#print axioms ZhangLS.Spec.bCanonicalArithmetic
#print axioms ZhangLS.Spec.b_canonical_arithmetic_product
#print axioms ZhangLS.Spec.b_canonical_norm_le_tau_two
#print axioms ZhangLS.Spec.b_psi_norm_le_tau_two
#print axioms ZhangLS.Spec.b_power_coefficient_majorant
#print axioms ZhangLS.Spec.b_moebius_coefficient_majorant
#print axioms ZhangLS.Spec.b_kappa_norm_le_tau_three
#print axioms ZhangLS.Spec.b_actual_ratio_coefficient_tau_five
#print axioms ZhangLS.Spec.b_paperP_one_le
#print axioms ZhangLS.Spec.b_h14_cutoff_le_P1
#print axioms ZhangLS.Spec.b_paperT_one_le
#print axioms ZhangLS.Spec.b_P2_le_half_power
#print axioms ZhangLS.Spec.b_product_cutoff_exact
#print axioms ZhangLS.Spec.b_source_H_literal
#print axioms ZhangLS.Spec.b_actual_H14_literal
#print axioms ZhangLS.Spec.b_actual_H12_literal
#print axioms ZhangLS.Spec.b_actual_H13_literal
#print axioms ZhangLS.Spec.b_four_source_coefficients_unchanged
#print axioms ZhangLS.Spec.b_repaired_rough_sum
#print axioms ZhangLS.Spec.b_actual_H14_endpoint
#print axioms ZhangLS.Spec.b_actual_P2_exact
#print axioms ZhangLS.Spec.b_actual_basis_at_one
#print axioms ZhangLS.Spec.b_actual_ratio_coefficient_at_one
