/- Generated central audit; staged only, not elaborated. -/
import ZhangLS.Spec.AppendixBRoughReplacementB1
import ZhangLS.Spec.AppendixBDivisorNuTail
import ZhangLS.Spec.AppendixBDivisorReplacementB1
import ZhangLS.Spec.AppendixBDivisorCoefficientB1
import ZhangLS.Spec.AppendixBDivisorB1Regressions
import ZhangLS.Spec.AppendixBKernelPerronBridge
import ZhangLS.Spec.AppendixBKernelModelCircle
import ZhangLS.Spec.AppendixBKernelZetaCircle
import ZhangLS.Spec.AppendixBKernelContour
import ZhangLS.Spec.AppendixBKernelRightLine
import ZhangLS.Spec.AppendixBKernelStripBoundary
import ZhangLS.Spec.AppendixBKernelBoundaryIntegrals
import ZhangLS.Spec.AppendixBKernelFullComparison
import ZhangLS.Spec.AppendixBKernelOriginalUniform
import ZhangLS.Spec.AppendixBKernelPhaseComparison
import ZhangLS.Spec.AppendixBKernelOriginalPhases
import ZhangLS.Spec.AppendixBKernelErrorDecay
import ZhangLS.Spec.AppendixBKernelRegressions
import ZhangLS.Spec.AppendixBRoughPrimeLog
import ZhangLS.Spec.AppendixBRoughRhoEuler
import ZhangLS.Spec.AppendixBRoughReplacementB2
import ZhangLS.Spec.AppendixBRoughWeightedReplacement
import ZhangLS.Spec.AppendixBRoughKernelReplacement
import ZhangLS.Spec.AppendixBTailSupport
import ZhangLS.Spec.AppendixBTailRamp
import ZhangLS.Spec.AppendixBTailGaussianMellin
import ZhangLS.Spec.AppendixBTailMultiplier
import ZhangLS.Spec.AppendixBTailRightBoundary
import ZhangLS.Spec.AppendixBTailOriginalRange
import ZhangLS.Spec.AppendixBTailLeftBoundary
import ZhangLS.Spec.AppendixBTailHorizontalBoundary
import ZhangLS.Spec.AppendixBTailContour
import ZhangLS.Spec.AppendixBTailGlobalContour
import ZhangLS.Spec.AppendixBTailBudgetDecay
import ZhangLS.Spec.AppendixBTailGaussianComparison
import ZhangLS.Spec.AppendixBTailUnsmoothing
import ZhangLS.Spec.AppendixBTailBoundaryMass
import ZhangLS.Spec.AppendixBTailFarBoundary
import ZhangLS.Spec.AppendixBTailRhoBounds
import ZhangLS.Spec.AppendixBTailSharpIntegral
import ZhangLS.Spec.AppendixBTailSharpKernel
import ZhangLS.Spec.AppendixBTailSharpFiniteIntegral
import ZhangLS.Spec.AppendixBTailFiniteUnsmoothing
import ZhangLS.Spec.AppendixBTailGaussianSplit
import ZhangLS.Spec.AppendixBTailFloorGeometry
import ZhangLS.Spec.AppendixBTailSourceUnsmoothing
import ZhangLS.Spec.AppendixBTailResidueRate
import ZhangLS.Spec.AppendixBTailTerminalResidue
import ZhangLS.Spec.AppendixBTailArithmeticComparison
import ZhangLS.Spec.AppendixBTailUnsmoothingDecay
import ZhangLS.Spec.AppendixBTailFinalAsymptotic
import ZhangLS.Spec.AppendixBTailRegressions
import ZhangLS.Spec.AppendixBTailH14Assembly
import ZhangLS.Spec.Lemma151ActualFiniteSupport
import ZhangLS.Spec.Lemma151ActualKernelFactors
import ZhangLS.Spec.Lemma151ActualPointwiseBudget
import ZhangLS.Spec.Lemma151ActualRoughRectangle
import ZhangLS.Spec.Lemma151ActualPointwiseAssembly
import ZhangLS.Spec.Lemma151ActualPointwiseDecay
import ZhangLS.Spec.Lemma151ActualPointwiseRegressions
import ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget
import ZhangLS.Spec.Lemma151ActualWeightedEulerBudget
import ZhangLS.Spec.Lemma151ActualWeightedPrefix
import ZhangLS.Spec.Lemma151ActualWeightedSourceBudget
import ZhangLS.Spec.Lemma151ActualWeightedApplication

set_option maxHeartbeats 12000000

open Lean Elab Command in
run_cmd do
  let env ← getEnv
  let expected : Array (Name × Name) := #[(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_Q),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_actual_b),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_actual_bpsi),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_beta_shifts),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_fourth_endpoint),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_fourth_endpoint._proof_1_1),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_original_A),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_ramified_n1),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_square_source),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_strict_source),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_strict_source._proof_1_1),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.appendixB_divisor_regression_zero_n1),
(`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.lemma151ArithmeticReplacementError.eq_1),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.appendixB_actual_b_B1_uniform),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.appendixB_actual_b_arithmetic_errors),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.appendixB_actual_b_factor_majorants),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.appendixB_optional_character_norm),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.appendixB_shifted_coefficient_factor_majorant),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.appendixB_shifted_coefficient_majorant),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.appendixB_actual_divisor_nu_tail),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.appendixB_actual_divisor_nu_tail._proof_1_2),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.appendixB_finite_weighted_cauchy),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.appendixB_tau_two_harmonic_energy),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.appendixB_tau_two_harmonic_energy._proof_1_1),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.appendixB_tau_two_paper_energy),
(`ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.lemma31PaperCutoff.eq_1),
(`ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.appendixB_divisor_arithmetic_error_explicit),
(`ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.appendixB_divisor_arithmetic_error_finite),
(`ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.appendixB_divisor_arithmetic_error_finite._proof_1_1),
(`ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.appendixB_divisor_weighted_B1_explicit),
(`ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.appendixB_divisor_weighted_B1_uniform),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_horizontal_bound),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.appendixB_left_boundary_bound._simp_1_7),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixBRegularIntegrand),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixBRegularIntegrand.eq_1),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixBRegularNumerator),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixB_actual_rectangle_circle),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixB_actual_rectangle_circle._proof_1_1),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixB_regular_integrand_agrees),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixB_regular_numerator_differentiableOn),
(`ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.appendixB_regular_rectangle_circle),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixBContourPolynomialConstant),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixBContourPolynomialConstant._proof_1),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixBContourPolynomialConstant._proof_2),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixBContourPolynomialConstant._proof_3),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixBContourPolynomialConstant._proof_4),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixB_contour_budget_eventually),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixB_contour_budget_nonneg),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixB_contour_budget_polynomial),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixB_contour_budget_polynomial._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixB_original_error_eventual_bound),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.appendixB_original_error_tendsto_zero),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixBContourBudget),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixBContourBudget._proof_1),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixBContourBudget._proof_2),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixBContourBudget._proof_3),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixBContourBudget._proof_4),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._proof_1_1),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_7),
(`ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.appendixB_full_kernel_quantitative._simp_1_8),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixBModelLeading),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixBModelLeading.eq_1),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_circle_eq_leading),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_circle_integral),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.appendixB_model_partial_fractions._simp_1_7),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_2),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_3),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_4),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_5),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_6),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalError._proof_7),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalFrequency.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixBOriginalGamma.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_alpha_logP),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_log_model_at_printed._simp_1_7),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_beta_perturbation),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_frequency_bounds),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_gamma_eq),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_gamma_lower),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_phase_budget),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_phase_budget._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_printed_constants_uniform),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.appendixB_original_printed_constants_uniform._proof_1_1),
(`ZhangLS.Spec.BCoefficientBounds, `ZhangLS.Spec.lemma151Beta6.eq_1),
(`ZhangLS.Spec.BCoefficientBounds, `ZhangLS.Spec.lemma151Beta7.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.lemma23PaperOffsetOne.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.lemma23PaperOffsetThree.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.lemma23PaperOffsetTwo.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalCutoff),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalCutoff._proof_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalExponent),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalExponent.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalFrequency),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalFrequency._proof_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalFrequency._proof_2),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalFrequency._proof_3),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalGamma),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalTCost),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalTCost._proof_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixBOriginalTCost.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixB_original_cutoff_log),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixB_original_cutoff_pos),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixB_original_cutoffs_eventually),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixB_original_full_kernels_uniform),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixB_original_gamma),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.appendixB_original_log_l1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.lemma151P1.eq_1),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.lemma151P3.eq_1),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixBFullKernelSum),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_full_kernel_perron),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_7),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_kernel_perron_term._simp_1_8),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_rho_dirichlet_series),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_twist_LSeries),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_twist_summable),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_twist_term),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.appendixB_twist_term._simp_1_1),
(`ZhangLS.Spec.BSourceKernels, `ZhangLS.Spec.lemma151Kernel.eq_1),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBLogModel),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBPhaseBudget),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBPhaseBudget._proof_1),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBPhaseBudget._proof_2),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBPhaseBudget._proof_3),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBPhaseBudget._proof_4),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixBPhaseBudget._proof_5),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_imaginary_exp_lipschitz),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_imaginary_exp_norm),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_log_model_stability),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.appendixB_model_as_log_model._simp_1_7),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_H14_complement_pointwise),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_H14_endpoint_separate),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_P2_source_expanded),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_beta_one_source),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_beta_three_source),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_beta_two_source),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_full_kernel_finite_sum),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_full_kernel_strict_product_endpoint),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_kernel_strict_endpoint),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_kernel_zero_index),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_literal_B3_tail_zero),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_original_P1),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_original_P2),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_original_P3),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_original_gamma_P1),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_original_gamma_P2),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_original_gamma_P3),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_printed_e1_prime),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_printed_e2),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_printed_e3),
(`ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.appendixB_source_full_kernel_asymptotics),
(`ZhangLS.Spec.AppendixBKernelRightLine, `ZhangLS.Spec.appendixB_integrand_eq_log_kernel),
(`ZhangLS.Spec.AppendixBKernelRightLine, `ZhangLS.Spec.appendixB_right_line_integrable),
(`ZhangLS.Spec.AppendixBKernelRightLine, `ZhangLS.Spec.appendixB_right_ratio_bound),
(`ZhangLS.Spec.AppendixBKernelRightLine, `ZhangLS.Spec.appendixB_right_tails),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.AppendixBContourPoint),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.AppendixBContourPoint._proof_1),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixBContourHeight),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixBContourHeight._proof_1),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixBContourMajorant),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixBContourMajorant._proof_1),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixB_actual_contour_ratio_bound),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixB_actual_contour_ratio_bound._proof_1_1),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.appendixB_extended_strip_bounds),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixBZetaCircle),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixBZetaCircle._proof_1),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixBZetaIntegrand),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_actual_circle_leading_error),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_circle_error),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_1),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_2),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_3),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_4),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_5),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_6),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.appendixB_zeta_ratio_regularized._simp_1_7),
(`ZhangLS.Spec.AppendixBRoughKernelReplacement, `ZhangLS.Spec.appendixB_actual_kernel_rhostar_to_full_uniform),
(`ZhangLS.Spec.AppendixBRoughKernelReplacement, `ZhangLS.Spec.appendixB_kernel_tsum_finite),
(`ZhangLS.Spec.AppendixBRoughKernelReplacement, `ZhangLS.Spec.appendixB_kernel_tsum_finite._proof_1_1),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_prime_log_mass),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_prime_log_mass_strict),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_1),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_2),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_3),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_4),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_5),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_6),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.appendixB_weighted_prefix_bound._simp_1_7),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_actual_nu_tail),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_actual_nu_tail._proof_1_1),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_rough_arithmetic_error_finite),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_rough_arithmetic_error_finite._proof_1_2),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_rough_gt_fourth),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_rough_gt_fourth._proof_1_1),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_rough_gt_fourth._proof_1_2),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_rough_gt_fourth._proof_1_3),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_weighted_B1_explicit),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.appendixB_weighted_B1_uniform),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixBRhoGlobalConstant),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixBRhoGlobalConstant._proof_1),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixBRhoGlobalConstant._proof_2),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixBRoughRemovalConstant),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixBRoughRemovalConstant._proof_1),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_nonrough_mass_exp_bound),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_nonrough_mass_finite),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_nonrough_small_prime),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_original_B2_explicit),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_original_B2_uniform),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_original_mass_exponent),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_original_mass_exponent._proof_1_1),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_original_rho_mass),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_original_rho_norm),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_prime_multiple_mass),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_replacement_alpha_scale),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_rho_global_constant_pos),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.appendixB_rough_removal_constant_pos),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixBRhoMass),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixBRhoMass.eq_1),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_prime_factor_log_sum),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_excess),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_series),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_1),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_2),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_3),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_4),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_5),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_6),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_local_tail._simp_1_7),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_euler),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_euler._proof_1_1),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_exp_bound),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_mul),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_nonneg),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_one),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_mass_zero),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_norm_exp_log),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_norm_le_index),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_prime_factorization),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_prime_norm),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_prime_power),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_prime_power._proof_1_1),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.appendixB_rho_prime_power._proof_1_2),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixBReplacementConstant),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixBReplacementConstant._proof_1),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixB_kernel_replacement_uniform),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixB_replacement_constant_pos),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixB_weighted_replacement_explicit),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixB_weighted_replacement_uniform),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.appendixB_weighted_rough_removal),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixBSharpTailError),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixBSharpTailError._proof_1),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixBSharpTailError._proof_2),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixBSharpTailError._proof_3),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixBSharpTailError._proof_4),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixB_actual_sharp_tail_quantitative),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.appendixB_actual_tail_to_exact_residue_uniform),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_interval_card_bound),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_interval_card_bound._proof_1_1),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_interval_harmonic_mass),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_1),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_2),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_3),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_4),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_5),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_6),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.appendixB_logarithmic_boundary_mass._simp_1_7),
(`ZhangLS.Spec.AppendixBTailBudgetDecay, `ZhangLS.Spec.appendixBTailContourBudget),
(`ZhangLS.Spec.AppendixBTailBudgetDecay, `ZhangLS.Spec.appendixBTailContourBudget._proof_1),
(`ZhangLS.Spec.AppendixBTailBudgetDecay, `ZhangLS.Spec.appendixB_tail_contour_budget_eventual_power),
(`ZhangLS.Spec.AppendixBTailBudgetDecay, `ZhangLS.Spec.appendixB_tail_contour_budget_polynomial),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixBTailContinuedIntegrand),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixBTailHolomorphicNumerator),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_actual_circle_residue),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_actual_circle_residue._simp_1_1),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_circle_residue),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_circle_residue._simp_1_1),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_continued_agrees),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_holomorphic_at_zero),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_numerator_differentiableOn),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_rectangle_circle),
(`ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.appendixB_tail_single_pole_decomposition),
(`ZhangLS.Spec.AppendixBTailFarBoundary, `ZhangLS.Spec.appendixB_far_gaussian_summable_bound),
(`ZhangLS.Spec.AppendixBTailFarBoundary, `ZhangLS.Spec.appendixB_far_gaussian_term_bound),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBExactTailErrorConstant),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBExactTailErrorConstant._proof_1),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBExactTailErrorConstant._proof_2),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBExactTailErrorConstant._proof_3),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBTerminalTailErrorConstant),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBTerminalTailErrorConstant._proof_1),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixBTerminalTailErrorConstant._proof_2),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_actual_tail_exact_residue_power),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_actual_tail_terminal_detailed),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_actual_tail_terminal_power),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_actual_tail_terminal_uniform),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_exact_tail_budget_eventual_power),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_sharp_tail_error_eventual_detailed),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.appendixB_sharp_tail_error_eventual_power),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.appendixBCutoffUnsmoothingBudget),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.appendixBCutoffUnsmoothingBudget._proof_1),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.appendixBCutoffUnsmoothingBudget._proof_2),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.appendixB_actual_rho_finite_error),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.appendixB_cutoff_budget_antitone),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.appendixB_harmonic_paper_floor),
(`ZhangLS.Spec.AppendixBTailFloorGeometry, `ZhangLS.Spec.appendixB_source_cutoff_le_p1),
(`ZhangLS.Spec.AppendixBTailFloorGeometry, `ZhangLS.Spec.appendixB_source_floor_geometry),
(`ZhangLS.Spec.AppendixBTailFloorGeometry, `ZhangLS.Spec.appendixB_two_p1_le_floor_p),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._proof_1_1),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_2),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_3),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_4),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_5),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_6),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_7),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.appendixB_source_gaussian_slice_quantitative._simp_1_8),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixBRhoGaussianIntegrand),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixBRhoGaussianIntegrand.eq_1),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixBRhoGaussianSeries),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixBSourceGaussianSlice),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_1),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_2),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_3),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_4),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_5),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_6),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_monomial_LSeries_term._simp_1_7),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_rho_gaussian_integrand_tsum),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_rho_gaussian_mellin),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_source_gaussian_integrand),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_source_gaussian_numerator),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_source_gaussian_slice_eq_sum),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.appendixB_source_gaussian_slice_mellin),
(`ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.appendixBFiniteGaussianSourceSlice),
(`ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.appendixB_rho_gaussian_finite_split),
(`ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.appendixB_rho_gaussian_finite_split._simp_1_1),
(`ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.appendixB_source_gaussian_eq_rho_series),
(`ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.appendixB_source_gaussian_finite_error),
(`ZhangLS.Spec.AppendixBTailGlobalContour, `ZhangLS.Spec.appendixB_tail_actual_rectangle_circle),
(`ZhangLS.Spec.AppendixBTailGlobalContour, `ZhangLS.Spec.appendixB_tail_actual_rectangle_circle._proof_1_1),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixBH14TerminalConstant),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixBH14TerminalConstant._proof_1),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixBH14TerminalConstant._proof_2),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixB_actual_h14_exact_residue_power),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixB_actual_h14_terminal_quantitative),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixB_actual_h14_terminal_uniform),
(`ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.appendixB_tail_residue_exact_shift_independence),
(`ZhangLS.Spec.AppendixBTailHorizontalBoundary, `ZhangLS.Spec.appendixB_tail_horizontal_bound),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_actual_tail_left_uniform),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_log_kernel_mono_negative),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_1),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_2),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_3),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_4),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_5),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_6),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.appendixB_tail_left_boundary_bound._simp_1_7),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_gaussian_multiplier_bound),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_1),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_2),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_3),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_4),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_5),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_6),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_linear_gaussian_bound._simp_1_7),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_source_power_bracket),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_1),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_2),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_3),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_4),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_5),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_6),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_full_kernel_factorization._simp_1_7),
(`ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.appendixB_tail_integrand_norm_transfer),
(`ZhangLS.Spec.AppendixBTailOriginalRange, `ZhangLS.Spec.appendixBOriginalCutoff.eq_1),
(`ZhangLS.Spec.AppendixBTailOriginalRange, `ZhangLS.Spec.appendixB_source_scale_log),
(`ZhangLS.Spec.AppendixBTailOriginalRange, `ZhangLS.Spec.appendixB_source_scales_uniform),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixBStrictMonomial),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixBStrictMonomial.eq_1),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_complement_ramp_identity),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_monomial_excludes_equality),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_positive_cpow_split),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._proof_1_9),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_2),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_3),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_4),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_5),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_6),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_7),
(`ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.appendixB_truncated_ramp_identity._simp_1_8),
(`ZhangLS.Spec.AppendixBTailRegressions, `ZhangLS.Spec.appendixB_actual_complement_endpoint),
(`ZhangLS.Spec.AppendixBTailRegressions, `ZhangLS.Spec.appendixB_printed_tail_literal),
(`ZhangLS.Spec.AppendixBTailRegressions, `ZhangLS.Spec.appendixB_terminal_tail_literal),
(`ZhangLS.Spec.AppendixBTailRegressions, `ZhangLS.Spec.appendixB_terminal_tail_sign),
(`ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.appendixB_actual_tail_beta_rate),
(`ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.appendixB_actual_tail_beta_rate._simp_1_1),
(`ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.appendixB_tail_model_beta_error),
(`ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.appendixB_tail_residue_local_error),
(`ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.appendixB_tail_zero_numerator_norm),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixBRhoMonomialCoefficient),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixBRhoMonomialCoefficient.eq_1),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixB_actual_rho_far_gaussian),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixB_actual_rho_finite_unsmoothing),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixB_global_rho_monomial_bound),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixB_log_ratio_step),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixB_original_rho_monomial_bound),
(`ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.appendixB_rho_monomial_norm),
(`ZhangLS.Spec.AppendixBTailRightBoundary, `ZhangLS.Spec.appendixB_log_kernel_mono_positive),
(`ZhangLS.Spec.AppendixBTailRightBoundary, `ZhangLS.Spec.appendixB_source_standard_line_mellin),
(`ZhangLS.Spec.AppendixBTailRightBoundary, `ZhangLS.Spec.appendixB_tail_right_tails),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixBSharpSourceSlice),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixBSharpSourceSlice.eq_1),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixBSharpSourceTerm),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixB_actual_complement_finite_integral),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixB_affine_log_step_intervalIntegrable),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixB_sharp_source_slice_intervalIntegrable),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixB_sharp_source_term_eq_log),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixB_sharp_source_term_integral),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.appendixB_sharp_source_term_intervalIntegrable),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_scaled_log_step),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_scaled_log_step._simp_1_1),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_scaled_step_difference_integral),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_strict_step_difference_integral),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_strict_step_interval),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_strict_step_interval._simp_1_1),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_strict_step_intervalIntegrable),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.appendixB_strict_step_intervalIntegrable._simp_1_1),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_actual_complement_step_integral),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_complement_finite_sum),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_integral),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_1),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_2),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_3),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_4),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_5),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_6),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_exponential_complement_ramp._simp_1_7),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_integer_log_cutoff),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_log_step_difference_integral),
(`ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.appendixB_paper_power_exp),
(`ZhangLS.Spec.AppendixBTailSourceUnsmoothing, `ZhangLS.Spec.appendixBSingleUnsmoothingBudget),
(`ZhangLS.Spec.AppendixBTailSourceUnsmoothing, `ZhangLS.Spec.appendixB_finite_gaussian_sharp_error),
(`ZhangLS.Spec.AppendixBTailSourceUnsmoothing, `ZhangLS.Spec.appendixB_source_unsmoothing_uniform),
(`ZhangLS.Spec.AppendixBTailSourceUnsmoothing, `ZhangLS.Spec.appendixB_source_unsmoothing_uniform._proof_1_1),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixBComplementKernel),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixBComplementKernel.eq_1),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixBComplementKernelSum),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixBTruncatedKernel),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixBTruncatedKernel.eq_1),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixBTruncatedKernelSum),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_actual_h14_sum),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_complement_terms_summable),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_complement_zero_at_or_above),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_complement_zero_below),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_full_eq_h14_add_complement),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_h14_is_actual_truncation),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_kernel_exact_partition),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_shifted_kernel_summable),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_shifted_kernel_support),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_tail_includes_equality),
(`ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.appendixB_truncated_terms_summable),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixBIntegratedExactTailResidue),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_actual_beta_ne_zero),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_actual_beta_ne_zero._proof_1_1),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_integrated_exact_tail_rate),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_integrated_original_leading_tail),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_integrated_tail_bstar_rate),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_1),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_2),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_3),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_4),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_5),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_6),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.appendixB_original_tail_leading_phase._simp_1_7),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixBGaussianBoundaryBand),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixBGaussianBoundaryBand.eq_1),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixBGaussianStepError),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixBGaussianStepError.eq_1),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixBStrictLogStep),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixBStrictLogStep.eq_1),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_finite_unsmoothing),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_finite_unsmoothing._simp_1_2),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_finite_unsmoothing._simp_1_3),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_step_endpoint),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_step_error_le_one),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_step_error_off_boundary),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.appendixB_gaussian_weight_unit_interval),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.appendixBUnsmoothingDecayConstant),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.appendixBUnsmoothingDecayConstant._proof_1),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.appendixBUnsmoothingDecayConstant._proof_2),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.appendixB_unsmoothing_budget_eventual_power),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.appendixB_unsmoothing_budget_polynomial),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.appendixB_unsmoothing_decay_constant_pos),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_b_first_cutoff_le_P),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_b_product_cutoff_le_P),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_b_second_cutoff_le_P),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_divisor_coordinates),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_kernel_pair_product_le_floor),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_psi_arithmetic_sum_finite),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.actual151_weight_tsum_finite),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FirstConstant),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FirstConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FirstConstant._proof_2),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FirstConstant.eq_1),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FirstError),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FullFactor),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151FullFactor.eq_1),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151KernelError),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151MainConstant),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151RoughFactor),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151SecondConstant),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151SecondConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151SecondConstant.eq_1),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151SecondError),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151_bounded_rough_removal_uniform),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151_full_factor_linear),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151_full_factor_linear._simp_1_1),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151_full_factors_uniform),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151_linear_error),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.actual151_rough_factors_uniform),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.Lemma151RepairedQuantitativeTarget),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_main_constant_residue),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_repaired_quantitative),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_repaired_quantitative._proof_1_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_repaired_quantitative._proof_1_2),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_repaired_quantitative_character),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_repaired_quantitative_character._proof_1_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.actual151_rho_convolution_collision),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151FirstConstantBound),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151NuError),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151NuError._proof_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151PointwiseError),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151ProductError),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151SecondConstantBound),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151_divisor_products_uniform),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151_first_constant_le),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151_product_error),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151_rhostar_to_rho_uniform),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.actual151_second_constant_le),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FirstErrorConstant),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_2),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_3),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_4),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_5),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_6),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151FullErrorConstant._proof_7),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151PointwiseConstant),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151PointwiseConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151Rate),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151Rate._proof_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151Rate._proof_2),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151Rate.eq_1),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151SecondErrorConstant),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_collision_le_rate),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_factor_error_rates),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_outer_four_log_scale),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_pointwise_error_rate),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_pointwise_error_tendsto_zero),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_rate_le_one),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_rate_nonneg),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_repaired_power_uniform),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.actual151_zpow_le_rate),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_P2),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_actual_beta),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_common_threshold),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_floor_endpoint),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_literal_target),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_product_cutoff),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_ramified_sum),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_rate),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_source_basis),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_strict_h14),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.actual151_regression_tail_constant),
(`ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.actual151_b_weight_rough_rectangle),
(`ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.actual151_psi_arithmetic_sum_rectangle),
(`ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.actual151_rho_rough_rectangle),
(`ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.actual151_rough_domain_factor_closed),
(`ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.actual151_rough_domain_positive),
(`ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.actual151PaperVarpi),
(`ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.actual151PaperVarpi.eq_1),
(`ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.actual151_actual_M_weighted_substitution_uniform),
(`ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.actual151_actual_weighted_substitution_uniform),
(`ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.actual151_pointwise_constant_nonneg),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151WeightedEulerConstant),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151WeightedEulerConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151WeightedEulerPrimeConstant),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151WeightedEulerPrimeConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_norm_term_real),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_one_add_four_le_inv_four),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_prime_monomial_real),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_abs_euler_bound),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_abs_real_series_bound),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_euler_constant_pos),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_euler_majorant_summable),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_euler_prime_constant_nonneg),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_finite_correction_bound),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.actual151_weighted_local_euler_bound),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_Icc_prefix_rankin),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_abs_real_series_summable),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_finite_prefix_L_22_5_of_zeta),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_finite_prefix_log_fourth_of_zeta),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_finite_prefix_rankin),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_norm_lseries_term_real),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_norm_riemannZeta_real_le),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_sigma_gt_one),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_1),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_2),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_3),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_4),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_5),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_6),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_rankin_term_le._simp_1_7),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_real_zeta_div_series_le),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_real_zeta_series_le),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.actual151_strict_prefix_rankin),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151WeightedPrimeTailConstant),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151WeightedPrimeTailConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151WeightedPrimeTailConstant._proof_2),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151WeightedPrimeTailConstant._proof_3),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151WeightedPrimeTailConstant.eq_1),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_local_chi_varpi_at_prime),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_local_weighted_prime_norm),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_weighted_local_norm_series),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_weighted_prime_norm),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_weighted_prime_power_tail),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_weighted_prime_tail_constant_nonneg),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.actual151_weighted_prime_tail_majorant_summable),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151WeightedPrefixConstant),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151WeightedPrefixConstant._proof_1),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151WeightedPrefixConstant.eq_1),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151_actual_coefficient_prefix_bound),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151_actual_paper_varpi_prefix),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151_actual_varpi_weight_prefix_bound),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151_weighted_prefix_constant_pos),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, `ZhangLS.Spec.actual151_weighted_prefix_error_scale)]
  let expectedOwners : Array (Name × Nat) := #[(`ZhangLS.Spec.AppendixBDivisorB1Regressions, 13),
(`ZhangLS.Spec.AppendixBDivisorCoefficientB1, 6),
(`ZhangLS.Spec.AppendixBDivisorNuTail, 7),
(`ZhangLS.Spec.AppendixBDivisorReplacementB1, 5),
(`ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, 9),
(`ZhangLS.Spec.AppendixBKernelContour, 8),
(`ZhangLS.Spec.AppendixBKernelErrorDecay, 11),
(`ZhangLS.Spec.AppendixBKernelFullComparison, 14),
(`ZhangLS.Spec.AppendixBKernelModelCircle, 12),
(`ZhangLS.Spec.AppendixBKernelOriginalPhases, 30),
(`ZhangLS.Spec.AppendixBKernelOriginalUniform, 20),
(`ZhangLS.Spec.AppendixBKernelPerronBridge, 15),
(`ZhangLS.Spec.AppendixBKernelPhaseComparison, 18),
(`ZhangLS.Spec.AppendixBKernelRegressions, 21),
(`ZhangLS.Spec.AppendixBKernelRightLine, 4),
(`ZhangLS.Spec.AppendixBKernelStripBoundary, 9),
(`ZhangLS.Spec.AppendixBKernelZetaCircle, 13),
(`ZhangLS.Spec.AppendixBRoughKernelReplacement, 3),
(`ZhangLS.Spec.AppendixBRoughPrimeLog, 10),
(`ZhangLS.Spec.AppendixBRoughReplacementB1, 10),
(`ZhangLS.Spec.AppendixBRoughReplacementB2, 18),
(`ZhangLS.Spec.AppendixBRoughRhoEuler, 27),
(`ZhangLS.Spec.AppendixBRoughWeightedReplacement, 7),
(`ZhangLS.Spec.AppendixBTailArithmeticComparison, 7),
(`ZhangLS.Spec.AppendixBTailBoundaryMass, 11),
(`ZhangLS.Spec.AppendixBTailBudgetDecay, 4),
(`ZhangLS.Spec.AppendixBTailContour, 11),
(`ZhangLS.Spec.AppendixBTailFarBoundary, 2),
(`ZhangLS.Spec.AppendixBTailFinalAsymptotic, 14),
(`ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, 6),
(`ZhangLS.Spec.AppendixBTailFloorGeometry, 3),
(`ZhangLS.Spec.AppendixBTailGaussianComparison, 9),
(`ZhangLS.Spec.AppendixBTailGaussianMellin, 18),
(`ZhangLS.Spec.AppendixBTailGaussianSplit, 5),
(`ZhangLS.Spec.AppendixBTailGlobalContour, 2),
(`ZhangLS.Spec.AppendixBTailH14Assembly, 7),
(`ZhangLS.Spec.AppendixBTailHorizontalBoundary, 1),
(`ZhangLS.Spec.AppendixBTailLeftBoundary, 10),
(`ZhangLS.Spec.AppendixBTailMultiplier, 19),
(`ZhangLS.Spec.AppendixBTailOriginalRange, 3),
(`ZhangLS.Spec.AppendixBTailRamp, 14),
(`ZhangLS.Spec.AppendixBTailRegressions, 4),
(`ZhangLS.Spec.AppendixBTailResidueRate, 5),
(`ZhangLS.Spec.AppendixBTailRhoBounds, 8),
(`ZhangLS.Spec.AppendixBTailRightBoundary, 3),
(`ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, 9),
(`ZhangLS.Spec.AppendixBTailSharpIntegral, 8),
(`ZhangLS.Spec.AppendixBTailSharpKernel, 14),
(`ZhangLS.Spec.AppendixBTailSourceUnsmoothing, 4),
(`ZhangLS.Spec.AppendixBTailSupport, 17),
(`ZhangLS.Spec.AppendixBTailTerminalResidue, 14),
(`ZhangLS.Spec.AppendixBTailUnsmoothing, 13),
(`ZhangLS.Spec.AppendixBTailUnsmoothingDecay, 6),
(`ZhangLS.Spec.BCoefficientBounds, 2),
(`ZhangLS.Spec.BSourceKernels, 1),
(`ZhangLS.Spec.Lemma151ActualFiniteSupport, 7),
(`ZhangLS.Spec.Lemma151ActualKernelFactors, 20),
(`ZhangLS.Spec.Lemma151ActualPointwiseAssembly, 8),
(`ZhangLS.Spec.Lemma151ActualPointwiseBudget, 11),
(`ZhangLS.Spec.Lemma151ActualPointwiseDecay, 25),
(`ZhangLS.Spec.Lemma151ActualPointwiseRegressions, 11),
(`ZhangLS.Spec.Lemma151ActualRoughRectangle, 5),
(`ZhangLS.Spec.Lemma151ActualWeightedApplication, 5),
(`ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, 14),
(`ZhangLS.Spec.Lemma151ActualWeightedPrefix, 19),
(`ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, 12),
(`ZhangLS.Spec.Lemma151ActualWeightedSourceBudget, 8)]
  let scopedOwners : Array Name := #[`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.AppendixBKernelBoundaryIntegrals, `ZhangLS.Spec.AppendixBKernelContour, `ZhangLS.Spec.AppendixBKernelErrorDecay, `ZhangLS.Spec.AppendixBKernelFullComparison, `ZhangLS.Spec.AppendixBKernelModelCircle, `ZhangLS.Spec.AppendixBKernelOriginalPhases, `ZhangLS.Spec.AppendixBKernelOriginalUniform, `ZhangLS.Spec.AppendixBKernelPerronBridge, `ZhangLS.Spec.AppendixBKernelPhaseComparison, `ZhangLS.Spec.AppendixBKernelRegressions, `ZhangLS.Spec.AppendixBKernelRightLine, `ZhangLS.Spec.AppendixBKernelStripBoundary, `ZhangLS.Spec.AppendixBKernelZetaCircle, `ZhangLS.Spec.AppendixBRoughKernelReplacement, `ZhangLS.Spec.AppendixBRoughPrimeLog, `ZhangLS.Spec.AppendixBRoughReplacementB1, `ZhangLS.Spec.AppendixBRoughReplacementB2, `ZhangLS.Spec.AppendixBRoughRhoEuler, `ZhangLS.Spec.AppendixBRoughWeightedReplacement, `ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.AppendixBTailBudgetDecay, `ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.AppendixBTailFarBoundary, `ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.AppendixBTailFloorGeometry, `ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.AppendixBTailGlobalContour, `ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.AppendixBTailHorizontalBoundary, `ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.AppendixBTailOriginalRange, `ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.AppendixBTailRegressions, `ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.AppendixBTailRightBoundary, `ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.AppendixBTailSourceUnsmoothing, `ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.Lemma151ActualWeightedSourceBudget]
  let supplements : Array (Name × Name) := #[(`ZhangLS.Spec.BCoefficientBounds, `ZhangLS.Spec.lemma151Beta6.eq_1),
(`ZhangLS.Spec.BCoefficientBounds, `ZhangLS.Spec.lemma151Beta7.eq_1),
(`ZhangLS.Spec.BSourceKernels, `ZhangLS.Spec.lemma151Kernel.eq_1)]
  let newOwners : Array Name := #[`ZhangLS.Spec.AppendixBDivisorB1Regressions, `ZhangLS.Spec.AppendixBDivisorCoefficientB1, `ZhangLS.Spec.AppendixBDivisorNuTail, `ZhangLS.Spec.AppendixBDivisorReplacementB1, `ZhangLS.Spec.AppendixBTailArithmeticComparison, `ZhangLS.Spec.AppendixBTailBoundaryMass, `ZhangLS.Spec.AppendixBTailBudgetDecay, `ZhangLS.Spec.AppendixBTailContour, `ZhangLS.Spec.AppendixBTailFarBoundary, `ZhangLS.Spec.AppendixBTailFinalAsymptotic, `ZhangLS.Spec.AppendixBTailFiniteUnsmoothing, `ZhangLS.Spec.AppendixBTailFloorGeometry, `ZhangLS.Spec.AppendixBTailGaussianComparison, `ZhangLS.Spec.AppendixBTailGaussianMellin, `ZhangLS.Spec.AppendixBTailGaussianSplit, `ZhangLS.Spec.AppendixBTailGlobalContour, `ZhangLS.Spec.AppendixBTailH14Assembly, `ZhangLS.Spec.AppendixBTailHorizontalBoundary, `ZhangLS.Spec.AppendixBTailLeftBoundary, `ZhangLS.Spec.AppendixBTailMultiplier, `ZhangLS.Spec.AppendixBTailOriginalRange, `ZhangLS.Spec.AppendixBTailRamp, `ZhangLS.Spec.AppendixBTailRegressions, `ZhangLS.Spec.AppendixBTailResidueRate, `ZhangLS.Spec.AppendixBTailRhoBounds, `ZhangLS.Spec.AppendixBTailRightBoundary, `ZhangLS.Spec.AppendixBTailSharpFiniteIntegral, `ZhangLS.Spec.AppendixBTailSharpIntegral, `ZhangLS.Spec.AppendixBTailSharpKernel, `ZhangLS.Spec.AppendixBTailSourceUnsmoothing, `ZhangLS.Spec.AppendixBTailSupport, `ZhangLS.Spec.AppendixBTailTerminalResidue, `ZhangLS.Spec.AppendixBTailUnsmoothing, `ZhangLS.Spec.AppendixBTailUnsmoothingDecay, `ZhangLS.Spec.Lemma151ActualFiniteSupport, `ZhangLS.Spec.Lemma151ActualKernelFactors, `ZhangLS.Spec.Lemma151ActualPointwiseAssembly, `ZhangLS.Spec.Lemma151ActualPointwiseBudget, `ZhangLS.Spec.Lemma151ActualPointwiseDecay, `ZhangLS.Spec.Lemma151ActualPointwiseRegressions, `ZhangLS.Spec.Lemma151ActualRoughRectangle, `ZhangLS.Spec.Lemma151ActualWeightedApplication, `ZhangLS.Spec.Lemma151ActualWeightedEulerBudget, `ZhangLS.Spec.Lemma151ActualWeightedPrefix, `ZhangLS.Spec.Lemma151ActualWeightedPrimeBudget, `ZhangLS.Spec.Lemma151ActualWeightedSourceBudget]
  let forbiddenFlatModules : Array Name := #[`ActualFiniteSupport, `ActualKernelFactors, `ActualPointwiseAssembly, `ActualPointwiseBudget, `ActualPointwiseDecay, `ActualPointwiseRegressions, `ActualRoughRectangle, `ActualWeightedApplication, `ActualWeightedEulerBudget, `ActualWeightedPrefix, `ActualWeightedPrimeBudget, `ActualWeightedSourceBudget, `DivisorB1Regressions, `DivisorCoefficientB1, `DivisorNuTail, `DivisorReplacementB1, `KernelBoundaryIntegrals, `KernelContour, `KernelErrorDecay, `KernelFullComparison, `KernelModelCircle, `KernelOriginalPhases, `KernelOriginalUniform, `KernelPerronBridge, `KernelPhaseComparison, `KernelRegressions, `KernelRightLine, `KernelStripBoundary, `KernelZetaCircle, `RoughKernelReplacement, `RoughPrimeLog, `RoughReplacementB1, `RoughReplacementB2, `RoughRhoEuler, `RoughWeightedReplacement, `TailArithmeticComparison, `TailBoundaryMass, `TailBudgetDecay, `TailContour, `TailFarBoundary, `TailFinalAsymptotic, `TailFiniteUnsmoothing, `TailFloorGeometry, `TailGaussianComparison, `TailGaussianMellin, `TailGaussianSplit, `TailGlobalContour, `TailH14Assembly, `TailHorizontalBoundary, `TailLeftBoundary, `TailMultiplier, `TailOriginalRange, `TailRamp, `TailRegressions, `TailResidueRate, `TailRhoBounds, `TailRightBoundary, `TailSharpFiniteIntegral, `TailSharpIntegral, `TailSharpKernel, `TailSourceUnsmoothing, `TailSupport, `TailTerminalResidue, `TailUnsmoothing, `TailUnsmoothingDecay]
  let allowed : Array Name := #[`propext, `Classical.choice, `Quot.sound]
  let expectedNames := expected.map (fun p => p.2)
  unless expectedNames.toList.eraseDups.length == expected.size do
    throwError "Duplicate expected declaration name"
  unless expected.size == 689 && expectedOwners.size == 67 && scopedOwners.size == 65 &&
      newOwners.size == 46 && supplements.size == 3 do
    throwError "Changed exact ownership reconciliation scope"
  unless scopedOwners.toList.eraseDups.length == 65 do
    throwError "Duplicate scoped owner"
  for old in forbiddenFlatModules do
    if env.header.moduleNames.contains old then
      throwError "Flat module loaded alongside central owners: {old}"
  for pair in expectedOwners do
    unless pair.2 > 0 && env.header.moduleNames.contains pair.1 do
      throwError "Missing or vacuous declaration owner {pair.1}"
  for pair in expected do
    unless scopedOwners.contains pair.1 || supplements.contains pair do
      throwError "Unlisted source scope: {pair.1} {pair.2}"
    unless env.contains pair.2 do
      throwError "Missing expected declaration: {pair.2}"
    let some idx := env.getModuleIdxFor? pair.2 | throwError "Missing owner for {pair.2}"
    unless env.header.moduleNames[idx]! == pair.1 do
      throwError "Ownership changed for {pair.2}: expected {pair.1}, got {env.header.moduleNames[idx]!}"
  let mut seen : Array Name := #[]
  let mut ownerCounts : Array Nat := Array.replicate 67 0
  let mut newCount : Nat := 0
  let mut existingCount : Nat := 0
  let mut scopedCount : Nat := 0
  for (name, ci) in env.constants do
    if let some idx := env.getModuleIdxFor? name then
      let mod := env.header.moduleNames[idx]!
      if scopedOwners.contains mod then
        unless expected.contains (mod,name) do
          throwError "Uninventoried declaration in intended owner: {mod} {name}"
        if seen.contains name then
          throwError "Duplicate owned enumeration: {name}"
        seen := seen.push name
        scopedCount := scopedCount+1
        let axs ← collectAxioms name
        unless axs.all (fun a => allowed.contains a) do
          throwError "Unexpected owned axiom in {name}: {axs}"
        logInfo m!"OWNED_DECL {mod} {name} {axs}"
        for dep in ci.getUsedConstantsAsSet do
          logInfo m!"DECL_REF {name} {dep}"
        for i in [:expectedOwners.size] do
          if expectedOwners[i]!.1 == mod then
            ownerCounts := ownerCounts.set! i (ownerCounts[i]!+1)
        if newOwners.contains mod then
          newCount := newCount+1
        else
          existingCount := existingCount+1
  unless scopedCount == 686 do
    throwError "Scoped owner enumeration drift: {scopedCount}"
  for pair in supplements do
    let mod := pair.1
    let name := pair.2
    if scopedOwners.contains mod || seen.contains name then
      throwError "Supplement misclassified or duplicated: {mod} {name}"
    let some ci := env.find? name | throwError "Missing generated supplement: {name}"
    let axs ← collectAxioms name
    unless axs.all (fun a => allowed.contains a) do
      throwError "Unexpected generated supplement axiom: {name} {axs}"
    seen := seen.push name
    existingCount := existingCount+1
    logInfo m!"OWNED_DECL {mod} {name} {axs}"
    logInfo m!"GENERATED_SUPPLEMENT {mod} {name}"
    for dep in ci.getUsedConstantsAsSet do
      logInfo m!"DECL_REF {name} {dep}"
    for i in [:expectedOwners.size] do
      if expectedOwners[i]!.1 == mod then
        ownerCounts := ownerCounts.set! i (ownerCounts[i]!+1)
  for name in expectedNames do
    unless seen.contains name do
      throwError "Expected name absent from audit: {name}"
  for i in [:expectedOwners.size] do
    let pair := expectedOwners[i]!
    let n := ownerCounts[i]!
    unless n == pair.2 && n > 0 do
      throwError "Owned owner count drift: {pair.1} {n} expected {pair.2}"
    logInfo m!"OWNED_OWNER_COUNT {pair.1} {n}"
  unless seen.size == 689 && newCount == 427 && existingCount == 262 do
    throwError "Owned scope drift: total={seen.size}, new={newCount}, existing={existingCount}"
  for mod in env.header.moduleNames do
    logInfo m!"LOADED_MODULE {mod}"
  logInfo m!"OWNED_TOTAL {seen.size} NEW {newCount} EXISTING {existingCount} OWNERS {expectedOwners.size}"
  logInfo m!"OWNED_SCOPE {scopedCount} OWNERS {scopedOwners.size} SUPPLEMENTS {supplements.size}"
  logInfo "CENTRAL_OWNED_AUDIT_PASS"
