import audit.DivisorConductorBlockMomentsRegression

/-! Defining-module ownership covers public declarations, generated helpers,
and every endpoint regression. Full elaborated types and transitive axioms
are exported for inspection; the final inventory pins all names and types. -/
set_option autoImplicit false
set_option maxHeartbeats 24000000
set_option maxRecDepth 10000
set_option pp.all true
set_option pp.privateNames true
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.maxSteps 10000000
set_option pp.universes true

open Lean Elab Command in
run_cmd do
  let env ← getEnv
  let moduleNames := env.header.moduleNames
  let out ← IO.getStdout
  let owners : Array Name := #[
    `ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions,
    `ZhangLS.Spec.DivisorConductorBlockMomentsEnergy,
    `ZhangLS.Spec.DivisorConductorBlockMomentsLong,
    `ZhangLS.Spec.DivisorConductorBlockMomentsPrime,
    `ZhangLS.Spec.DivisorConductorBlockMomentsCauchy,
    `audit.DivisorConductorBlockMomentsRegression
  ]
  -- BEGIN PINS
  let expectedOwned : Array (Name × Name) := #[
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.finite_cauchy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_paper_prime_cauchy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_prime_cauchy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock._proof_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.CoefficientBound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant._proof_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant._proof_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant_pos),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli._proof_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli.eq_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment._proof_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._proof_1_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_3),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_4),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_5),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_6),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.logWeight),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.logWeight_nonneg),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longCoefficient),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longEnvelope),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longEnvelope_nonneg),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices._proof_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices.eq_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_positive),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_positive._proof_1_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_subset),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial_coefficient_sum),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longPositiveIndices),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli._simp_1_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli._simp_1_3),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._proof_1_4),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._proof_1_5),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._simp_1_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._simp_1_3),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.positiveLongPolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.positiveLongPolynomial_eq),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.dilated_coefficient_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.longCoefficient_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_card_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._proof_1_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_3),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_4),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_5),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_6),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_7),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_8),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_3),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_4),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_5),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_6),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_7),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.norm_sum_sq_le_card_energy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_block_strong),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_2),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_3),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_4),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_5),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_6),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_7),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.positive_long_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.positive_long_block_strong),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.imaginary_power_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.paperPrimePolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.paper_prime_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient.eq_1),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient_norm_le),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial_conjugate_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_coefficient_energy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_nontrivial_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_one_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_support_card),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment.eq_1),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial.eq_1),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock.eq_1),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial.eq_1),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.actual_prime_phase_norm),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.coefficient_bound_zero_forces_zero),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.coefficient_zero_bound),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_fractional_lower_included),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_fractional_upper_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_level_one_retained),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_real_lower_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_upper_open),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_zero_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_zero_excluded._simp_1_1),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.empty_prime_polynomial),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.exact_prime_minus_one),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.finite_cauchy_zero_endpoint),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_lower_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_lower_next_integer),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_upper_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_upper_inclusive),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_above_upper_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_below_lower_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_lower_inclusive),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_upper_inclusive),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.mask_keeps_coprime),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.mask_removes_lower_endpoint),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.nonunit_prime_vanishes),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.positive_imaginary_phase_norm),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.positive_index_interface),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.singleton_prime_bound),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.singleton_prime_bound._simp_1_1),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_block),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_constant_allowed),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_constant_allows_arbitrary_b_zero),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_long_index_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_polynomial)
  ]
  let expectedTypes : Array (Name × UInt64 × String) := #[
    (`ZhangLS.Spec.DivisorConductorBlockMoments.finite_cauchy, 2528360712067536179, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_paper_prime_cauchy, 14985599299555928244, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_prime_cauchy, 2824166886664265207, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock, 12151672506443674771, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock._proof_1, 1388598209486740759, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.CoefficientBound, 1915154737273284002, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant._proof_1, 5185406405428909789, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant._proof_2, 3457767388364009917, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant_pos, 585771699928698159, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli, 787860297730492024, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli._proof_1, 14647379146910394343, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli.eq_1, 5377003790894349586, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment, 14462456629455177238, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment._proof_1, 1388598209486740759, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial, 7182544775738790959, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._proof_1_1, 14618577181997792813, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_2, 6306083560453471106, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_3, 1988649516832762782, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_4, 5581755817566308493, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_5, 6974893438119822849, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial._simp_1_6, 14690689516260712981, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.logWeight, 15634331321698339388, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.logWeight_nonneg, 3228421585111850670, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longCoefficient, 16502731452339349087, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longEnvelope, 18332051000808571277, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longEnvelope_nonneg, 1676341877589718975, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices, 4840612821566391795, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices._proof_1, 772565646570335038, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices.eq_1, 9883793644761890741, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_positive, 7535327730864475618, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_positive._proof_1_1, 5868572843607078093, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_subset, 5421942090292159070, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial, 19179566705233328, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial_coefficient_sum, 5475515220000035364, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longPositiveIndices, 4205031415274749097, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli, 4005759028391301332, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli._simp_1_2, 1988649516832762782, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli._simp_1_3, 10178972178374386679, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices, 6442595471378940157, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._proof_1_4, 13103590493734262127, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._proof_1_5, 17801833506488056070, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._simp_1_2, 1988649516832762782, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices._simp_1_3, 10178972178374386679, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.positiveLongPolynomial, 3316457231610167267, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.positiveLongPolynomial_eq, 3672084749312634054, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.dilated_coefficient_bound, 11111279435316976525, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longCoefficient_norm, 12523332563362345770, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_card_bound, 17790626075897695398, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy, 17227339377776692984, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._proof_1_1, 11377723163758357459, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_2, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_3, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_4, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_5, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_6, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_7, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy._simp_1_8, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment, 15575801493029128125, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.norm_sum_sq_le_card_energy, 9051442968918345020, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_block_bound, 15915481508650756305, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_block_strong, 12284578011664139295, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment, 7340177901068540240, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.positive_long_block_bound, 5351892076775340624, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.positive_long_block_strong, 11022677837925257074, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.imaginary_power_norm, 15975716676309828859, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.paperPrimePolynomial, 17524784628489891574, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.paper_prime_block_bound, 9732497822513441517, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient, 16819396422472657446, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient.eq_1, 17028684568495853622, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient_norm, 8449917260921341947, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient_norm_le, 17676588139224295286, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial, 7702952341724510759, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial_conjugate_norm, 7413790132444056365, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.prime_block_bound, 1185259633294902530, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.prime_coefficient_energy, 18206716753497419112, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.prime_nontrivial_moment, 7254840133122327711, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.prime_one_moment, 16065552828464313376, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.prime_support_card, 2244113836790651337, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment.eq_1, 7987804798864704282, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial.eq_1, 16963813955062473879, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock.eq_1, 1810850277947021093, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial.eq_1, 17828996111001802176, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.actual_prime_phase_norm, 8478871494505313838, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.coefficient_bound_zero_forces_zero, 9407435848236737798, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.coefficient_zero_bound, 14728938142409788311, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_fractional_lower_included, 4450077930646844062, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_fractional_upper_excluded, 16978764044135963516, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_level_one_retained, 16303487476967698677, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_real_lower_excluded, 2268114834988056460, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_upper_open, 16062380366177408293, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_zero_excluded, 18281866506783580579, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_zero_excluded._simp_1_1, 10744148571523976384, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.empty_prime_polynomial, 8685858424861622800, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.exact_prime_minus_one, 20952411173350866, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.finite_cauchy_zero_endpoint, 10571580541189936751, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_lower_excluded, 11760775333271008999, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_lower_next_integer, 16206857595398406116, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_upper_excluded, 1171973789677413603, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_upper_inclusive, 17632794546854078409, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_above_upper_excluded, 2062384832873511013, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_below_lower_excluded, 5544892178067091822, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_lower_inclusive, 9161902994546911636, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_upper_inclusive, 11913903663275358396, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.mask_keeps_coprime, 891005297856872229, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.mask_removes_lower_endpoint, 4882957561721256109, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.nonunit_prime_vanishes, 2041662582949136763, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.positive_imaginary_phase_norm, 8166580602721788833, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.positive_index_interface, 8312356810207275903, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.singleton_prime_bound, 15586212703208764970, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.singleton_prime_bound._simp_1_1, 6974893438119822849, "[`u_1]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_block, 17248943433587575074, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_constant_allowed, 7860666054584255172, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_constant_allows_arbitrary_b_zero, 1125985716477231665, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_long_index_excluded, 7449218818281490881, "[]"),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_polynomial, 9999389972983092711, "[]")
  ]
  let expectedPublic : Array (Name × Name) := #[
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.finite_cauchy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_paper_prime_cauchy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_prime_cauchy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsCauchy, `ZhangLS.Spec.DivisorConductorBlockMoments.mixedBlock),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.CoefficientBound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockConstant_pos),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockModuli),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.blockMoment_le_one_add_nontrivial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.logWeight),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.logWeight_nonneg),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longCoefficient),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longEnvelope),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longEnvelope_nonneg),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_positive),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_subset),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longPolynomial_coefficient_sum),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.longPositiveIndices),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_blockModuli),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.mem_longIndices),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.positiveLongPolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsDefinitions, `ZhangLS.Spec.DivisorConductorBlockMoments.positiveLongPolynomial_eq),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.dilated_coefficient_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.longCoefficient_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.longIndices_card_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_coefficient_energy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.long_one_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsEnergy, `ZhangLS.Spec.DivisorConductorBlockMoments.norm_sum_sq_le_card_energy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_block_strong),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.long_nontrivial_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.positive_long_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsLong, `ZhangLS.Spec.DivisorConductorBlockMoments.positive_long_block_strong),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.imaginary_power_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.paperPrimePolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.paper_prime_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primeCoefficient_norm_le),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.primePolynomial_conjugate_norm),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_block_bound),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_coefficient_energy),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_nontrivial_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_one_moment),
    (`ZhangLS.Spec.DivisorConductorBlockMomentsPrime, `ZhangLS.Spec.DivisorConductorBlockMoments.prime_support_card),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.actual_prime_phase_norm),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.coefficient_bound_zero_forces_zero),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.coefficient_zero_bound),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_fractional_lower_included),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_fractional_upper_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_level_one_retained),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_real_lower_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_upper_open),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.conductor_zero_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.empty_prime_polynomial),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.exact_prime_minus_one),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.finite_cauchy_zero_endpoint),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_lower_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_lower_next_integer),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_upper_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.fractional_upper_inclusive),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_above_upper_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_below_lower_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_lower_inclusive),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.long_upper_inclusive),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.mask_keeps_coprime),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.mask_removes_lower_endpoint),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.nonunit_prime_vanishes),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.positive_imaginary_phase_norm),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.positive_index_interface),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.singleton_prime_bound),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_block),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_constant_allowed),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_constant_allows_arbitrary_b_zero),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_long_index_excluded),
    (`audit.DivisorConductorBlockMomentsRegression, `ZhangLS.Spec.DivisorConductorBlockMomentsRegression.zero_polynomial)
  ]
  -- END PINS
  let mut seen : Array (Name × Name) := #[]
  for (name, ci) in env.constants do
    if let some idx := env.getModuleIdxFor? name then
      let owner := moduleNames[idx]!
      if owners.contains owner then
        if seen.contains (owner, name) then throwError "Duplicate owned declaration {name}"
        if ci.isAxiom then throwError "Owned axiom {name}"
        let axs ← collectAxioms name
        unless axs.all (fun a => a == ``propext || a == ``Classical.choice || a == ``Quot.sound) do
          throwError "Nonstandard transitive axiom {name}: {axs}"
        let typePretty ← liftTermElabM <| Meta.ppExpr ci.type
        unless expectedOwned.isEmpty do
          unless expectedOwned.contains (owner, name) do
            throwError "Unexpected defining-module/name pair {owner} {name}"
          let some (_, pinnedType, pinnedUniverses) := expectedTypes.find? (fun p => p.1 == name)
            | throwError "Missing type pin {name}"
          unless hash typePretty.pretty == pinnedType do
            throwError "Full elaborated type fingerprint drift {name}"
          unless reprStr ci.levelParams == pinnedUniverses do
            throwError "Universe parameter drift {name}"
        let row := Json.mkObj [
          ("owner", toJson owner.toString),
          ("name", toJson name.toString),
          ("public", toJson (expectedPublic.contains (owner, name))),
          ("type_repr", toJson (reprStr ci.type)),
          ("type_lean_hash64", toJson (toString (hash typePretty.pretty))),
          ("type_pretty", toJson typePretty.pretty),
          ("universe_parameters_repr", toJson (reprStr ci.levelParams)),
          ("axioms", toJson (axs.map Name.toString)),
          ("used_constants", toJson (ci.getUsedConstantsAsSet.toArray.map Name.toString))]
        out.putStrLn s!"DECLARATION_JSON {row.compress}"
        out.flush
        seen := seen.push (owner, name)
  unless expectedOwned.isEmpty do
    unless seen.size == expectedOwned.size && seen.size == expectedTypes.size do
      throwError "Owned declaration count drift: {seen.size}"
    for pair in expectedOwned do
      unless seen.contains pair do throwError "Missing owned declaration {pair.2}"
    for pair in expectedPublic do
      unless seen.contains pair do throwError "Missing explicit declaration {pair.2}"
  for owner in owners do
    out.putStrLn s!"OWNER_COUNT {owner} {(seen.filter (fun p => p.1 == owner)).size}"
  for mod in moduleNames do
    out.putStrLn s!"LOADED_MODULE {mod}"
  out.putStrLn s!"OWNERSHIP_TYPE_AXIOM_PASS {seen.size} PUBLIC {expectedPublic.size}"
  out.flush
