import ZhangLS.Spec.CoprimeProfileAbelArithmetic
import ZhangLS.Spec.FixedHDiagonalIBP
import ZhangLS.Spec.FixedHProfileBump
import ZhangLS.Spec.CoprimeProfileAbelSummatory
import ZhangLS.Spec.FixedHDiagonalAlgebra
import ZhangLS.Spec.FixedHProfileNormalization
import ZhangLS.Spec.CoprimeProfileAbelEuler
import ZhangLS.Spec.FixedHDiagonal
import ZhangLS.Spec.FixedHProfileWindow
import ZhangLS.Spec.CoprimeProfileAbelBound
import ZhangLS.Spec.FixedHProfileSequence
import ZhangLS.Spec.CoprimeProfileAbelFormula
import ZhangLS.Spec.FixedHProfileAdmissible
import ZhangLS.Spec.CoprimeProfileAbelProfile

/-! Exact defining-module provenance, complete elaborated types, and transitive axiom audit. -/
set_option autoImplicit false
set_option maxHeartbeats 24000000
set_option maxRecDepth 10000
set_option pp.all true
set_option pp.privateNames true
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.maxSteps 10000000

open Lean Elab Command in
run_cmd do
  let env ← getEnv
  let moduleNames := env.header.moduleNames
  let out ← IO.getStdout
  let owners : Array Name := #[
    `ZhangLS.Spec.CoprimeProfileAbelArithmetic,
    `ZhangLS.Spec.FixedHDiagonalIBP,
    `ZhangLS.Spec.FixedHProfileBump,
    `ZhangLS.Spec.CoprimeProfileAbelSummatory,
    `ZhangLS.Spec.FixedHDiagonalAlgebra,
    `ZhangLS.Spec.FixedHProfileNormalization,
    `ZhangLS.Spec.CoprimeProfileAbelEuler,
    `ZhangLS.Spec.FixedHDiagonal,
    `ZhangLS.Spec.FixedHProfileWindow,
    `ZhangLS.Spec.CoprimeProfileAbelBound,
    `ZhangLS.Spec.FixedHProfileSequence,
    `ZhangLS.Spec.CoprimeProfileAbelFormula,
    `ZhangLS.Spec.FixedHProfileAdmissible,
    `ZhangLS.Spec.CoprimeProfileAbelProfile
  ]
  let expectedPublic : Array (Name × Name) := #[
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.density),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitCount),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient_zero),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient_nonneg),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient_le_one),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_one),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobius_divisor_sum),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitCount_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobius_density),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.nat_division_error),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitCount_error),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitWeight),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitWeight_positive),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_convolution),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail_hasDerivAt),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail_continuous),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail_c2),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_eq_glue),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_contDiff),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_support),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_tsupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_midpoint),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_midpoint_pos),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_contDiff),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_tsupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_at_minus_one),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_third_derivative_not_zero),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.truncatedDensity),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight_abs_le),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.unitCount_scaled_error),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.finite_density_error),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.firstKernel),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.secondKernel),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.pure_imaginary_product),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.cyclic_coefficient),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaled_diagonal),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.normalization),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.beta_third_abs_bddAbove),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.beta_third_abs_le_normalization),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.normalization_pos),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_contDiff),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_abs_le_one),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_tsupport),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_not_zero),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_square_integral_pos),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_square_intervalIntegrable),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_deriv_square_intervalIntegrable),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda_pos),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.principal_character_nat),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.principal_LSeries),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.mobius_square_summable),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.coprime_mobius_LSeries_two),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.mobius_square_value_equation),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_euler_factorization),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.total_density_eq_main),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B_pos),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B_mul_alpha),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_scaled_shift),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.F),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.G),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_diagonal),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_diagonal_c2),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_contDiff),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_abs_le_one),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_tsupport),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.supported_endpoints),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.F0_endpoints),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_endpoints),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_support),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_not_zero),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_eq_zero_of_le),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_eq_zero_of_ge),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.density_nonneg),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.density_le_one),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant_pos),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant_le_one),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tail),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_error),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.requested_summatory_error),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_zero),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_eq_of_pos),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_norm_le_one),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_support_window),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_eq_zero_of_below),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_support_rpow),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_eq_zero_of_above),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_support_finite),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.summatory_zero_start),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.finite_abel),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.summatory_product_integrable),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.abel_remainder_identity),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.abel_remainder_bound),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.paperP_gt_one),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.upper_window_le_paper_cutoff),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.h_paper_admissible),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.h_paper_admissible_eventually),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.continuous_supported_endpoints),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv_continuousOn),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv_bound),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weighted_term_eq),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.logarithmic_window),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weighted_abel_identity),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weighted_abel_error),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.original_window_abel_error)
  ]
  let expectedOwned : Array (Name × Name) := #[
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient_le_one),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient_nonneg),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coefficient_zero),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.density),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight._proof_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobius_density),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.mobius_divisor_sum),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.nat_division_error),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius._proof_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.summatory_one),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_convolution),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_5),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_6),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_7),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitCount),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitCount_error),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitCount_mobius),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitWeight),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitWeight._proof_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitWeight.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelArithmetic, `ZhangLS.Spec.CoprimeProfileAbel.unitWeight_positive),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._proof_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._proof_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tail),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._proof_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.density_le_one),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.density_nonneg),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant_le_one),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant_pos),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.requested_summatory_error),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_error),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_5),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_6),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_7),
    (`ZhangLS.Spec.CoprimeProfileAbelBound, `ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_8),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.coprime_mobius_LSeries_two),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_euler_factorization),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_5),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_6),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_7),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.mobius_square_summable),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.mobius_square_value_equation),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.principal_LSeries),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.principal_character_nat),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.principal_character_nat._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelEuler, `ZhangLS.Spec.CoprimeProfileAbel.total_density_eq_main),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.abel_remainder_bound),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.abel_remainder_identity),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.finite_abel),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.summatory_product_integrable),
    (`ZhangLS.Spec.CoprimeProfileAbelFormula, `ZhangLS.Spec.CoprimeProfileAbel.summatory_zero_start),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.continuous_supported_endpoints),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.logarithmic_window),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.original_window_abel_error),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv_bound),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv_continuousOn),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_5),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_6),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_7),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_5),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_6),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_7),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval._proof_1_1),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval._proof_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weighted_abel_error),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weighted_abel_identity),
    (`ZhangLS.Spec.CoprimeProfileAbelProfile, `ZhangLS.Spec.CoprimeProfileAbel.weighted_term_eq),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.finite_density_error),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.finite_density_error._proof_1_4),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.finite_density_error._simp_1_2),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.finite_density_error._simp_1_3),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.mainConstant._proof_1),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight_abs_le),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.truncatedDensity),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.truncatedDensity.eq_1),
    (`ZhangLS.Spec.CoprimeProfileAbelSummatory, `ZhangLS.Spec.CoprimeProfileAbel.unitCount_scaled_error),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B.eq_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B_mul_alpha),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B_pos),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.B_pos._proof_1_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.F),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.F.eq_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.G),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.G._proof_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.G.eq_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta.eq_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._proof_1_1),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_3),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_4),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_5),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_6),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_7),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_8),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_9),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_diagonal),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_diagonal_c2),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_scaled_shift),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.FixedHDiagonal.paper_scaled_shift._simp_1_2),
    (`ZhangLS.Spec.FixedHDiagonal, `ZhangLS.Spec.lemma83PaperBeta.eq_1),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.cyclic_coefficient),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.cyclic_coefficient._simp_1_1),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.firstKernel),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.firstKernel.eq_1),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.pure_imaginary_product),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_1),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_2),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_3),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_4),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaledShift.eq_1),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.scaled_diagonal),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.secondKernel),
    (`ZhangLS.Spec.FixedHDiagonalAlgebra, `ZhangLS.Spec.FixedHDiagonal.secondKernel.eq_1),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail._simp_1_1),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail_c2),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail.eq_1),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail_continuous),
    (`ZhangLS.Spec.FixedHDiagonalIBP, `ZhangLS.Spec.FixedHDiagonal.tail_hasDerivAt),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.h_paper_admissible),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.h_paper_admissible_eventually),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.paperP_gt_one),
    (`ZhangLS.Spec.FixedHProfileAdmissible, `ZhangLS.Spec.FixedHProfile.upper_window_le_paper_cutoff),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta.eq_1),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_contDiff),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_at_minus_one),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_contDiff),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_derivative_tsupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_eq_glue),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_midpoint),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_midpoint_pos),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_support),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_support._simp_1_1),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_support._simp_1_2),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_third_derivative_not_zero),
    (`ZhangLS.Spec.FixedHProfileBump, `ZhangLS.Spec.FixedHProfile.beta_tsupport),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0.eq_1),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_abs_le_one),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_contDiff),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_deriv_square_intervalIntegrable),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_not_zero),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_square_integral_pos),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_square_intervalIntegrable),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.F0_tsupport),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.beta_third_abs_bddAbove),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.beta_third_abs_le_normalization),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda._proof_1),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda._proof_2),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda._proof_3),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.fixedLambda_pos),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.normalization),
    (`ZhangLS.Spec.FixedHProfileNormalization, `ZhangLS.Spec.FixedHProfile.normalization_pos),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h.eq_1),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_eq_of_pos),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_eq_zero_of_above),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_eq_zero_of_below),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_norm_le_one),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_support_finite),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_support_rpow),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_support_window),
    (`ZhangLS.Spec.FixedHProfileSequence, `ZhangLS.Spec.FixedHProfile.h_zero),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.F0_endpoints),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f._proof_1),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f._proof_2),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f._proof_3),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f.eq_1),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_abs_le_one),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_contDiff),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_endpoints),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_eq_zero_of_ge),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_eq_zero_of_le),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_hasCompactSupport),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_not_zero),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_support),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.f_tsupport),
    (`ZhangLS.Spec.FixedHProfileWindow, `ZhangLS.Spec.FixedHProfile.supported_endpoints)
  ]
  let expectedTypes : Array (Name × UInt64 × String) := #[
    (`ZhangLS.Spec.CoprimeProfileAbel.coefficient, 16903234750592840327, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coefficient.eq_1, 8671670039519751175, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coefficient_le_one, 3145667977242228122, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coefficient_nonneg, 13071308477373728562, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coefficient_zero, 2518413174746423619, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator, 15595701281617438785, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator._simp_1_1, 7944629515112915904, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator._simp_1_2, 7073196793349487485, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coprime_indicator._simp_1_3, 10021167310781535760, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density, 12957806670630576245, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight, 1169406107900591935, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight._proof_1, 7140515191383809158, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight.eq_1, 6304965696793054051, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobius_density, 10038783001576076539, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobius_divisor_sum, 13460955927305712577, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.nat_division_error, 6658452504640027568, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory, 6370292862807857508, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory.eq_1, 17430681676125385740, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius, 5074571827895296961, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius._proof_1_3, 11478445982872789890, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius._simp_1_1, 11547570301497195731, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_mobius._simp_1_2, 10178972178374386679, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_one, 15624319899284795547, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_convolution, 1182187568885373381, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_mobius, 7790098313563821530, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius, 13355610104252164186, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.totient_ratio_mobius._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitCount, 4673533967483203845, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitCount_error, 3444044107423149491, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitCount_mobius, 2447582806773486555, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitWeight, 1169406107900591935, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitWeight._proof_1, 12747824946911599052, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitWeight.eq_1, 8746183935801691802, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitWeight_positive, 10480570375026696168, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius, 4673533967483203845, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius.eq_1, 8311735259127935670, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference, 4964925915708768760, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._proof_1_3, 2512981855791478163, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._proof_1_4, 5047310409405867395, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._simp_1_1, 11547570301497195731, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_difference._simp_1_2, 8156274923563715324, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tail, 4198432561383223499, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto, 10222769678829625067, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._proof_1_4, 14723149539010500520, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._simp_1_1, 1602490517834037662, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._simp_1_2, 16280161512472886946, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.cumulativeMobius_tendsto._simp_1_3, 11547570301497195731, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_le_one, 13063692457290401335, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_nonneg, 13805969943688418131, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mainConstant_le_one, 12598877767828666136, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mainConstant_pos, 15464811286513592488, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.requested_summatory_error, 15644567686160769767, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_error, 1027313547768535030, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error, 12844812538868071590, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_2, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_3, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_4, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_5, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_6, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_7, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_integer_error._simp_1_8, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.coprime_mobius_LSeries_two, 5104029486603844404, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_euler_factorization, 17879351052851707645, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product, 17896527456629556806, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.density_prime_product._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mainConstant.eq_1, 11898700283311083169, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobius_square_summable, 17981526879527422025, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobius_square_value_equation, 1633067385094325661, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.principal_LSeries, 14204634346347863909, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.principal_character_nat, 14872158747959424510, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.principal_character_nat._simp_1_1, 14099781613356095600, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.total_density_eq_main, 2948161669182760747, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.abel_remainder_bound, 14965663447221694344, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.abel_remainder_identity, 11182681433632418581, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.finite_abel, 6493009074793043210, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_product_integrable, 13957827783205931240, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.summatory_zero_start, 15914377245292312440, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.continuous_supported_endpoints, 5113403718894520211, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.logarithmic_window, 6799994378312395010, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.original_window_abel_error, 5906954704830321910, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight, 6415094061868075564, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight.eq_1, 6198682352457645872, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv, 2224792839631818499, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv_bound, 17787800118667020771, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeightDeriv_continuousOn, 13370581722048762990, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt, 9480842127459349214, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_hasDerivAt._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral, 4484373662206230040, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_1, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_2, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_3, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_4, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_5, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_6, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.profileWeight_integral._simp_1_7, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum, 3716402505726530536, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval, 12811835181207585002, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval._proof_1_1, 17150237184315498175, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weightedProfileSum_eq_interval._proof_1_2, 2039958699467066210, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weighted_abel_error, 15611796212162096476, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weighted_abel_identity, 6876542733605849115, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.weighted_term_eq, 3784537592069314661, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.finite_density_error, 10367557416856360262, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.finite_density_error._proof_1_4, 10866729406952596944, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.finite_density_error._simp_1_2, 11547570301497195731, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.finite_density_error._simp_1_3, 10178972178374386679, "[`u_1]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mainConstant, 12957806670630576245, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mainConstant._proof_1, 883099696403560685, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.mobiusWeight_abs_le, 16562009006793663760, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.truncatedDensity, 4673533967483203845, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.truncatedDensity.eq_1, 17068391052303452147, "[]"),
    (`ZhangLS.Spec.CoprimeProfileAbel.unitCount_scaled_error, 14051492238267460079, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.B, 12957806670630576245, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.B.eq_1, 12723854418906526747, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.B_mul_alpha, 18048495795940200582, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.B_pos, 11755343472204168409, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.B_pos._proof_1_1, 8134426730283137314, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.F, 1195629802309565012, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.F.eq_1, 17903292239378017245, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.G, 6827810028779021445, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.G._proof_1, 14568674335733737352, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.G.eq_1, 13020163750177679114, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta, 300697104076658338, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta.eq_1, 8435510596683245281, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq, 4481902922594201668, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._proof_1_1, 8134426730283137314, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_3, 6033590925971773593, "[`u_2]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_4, 13972439555833037651, "[`u_2]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_5, 16412815542536123252, "[`u_2]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_6, 2173808416608830180, "[`u_1]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_7, 7579211897750796183, "[`u_1]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_8, 5885927816594865294, "[`u_3]"),
    (`ZhangLS.Spec.FixedHDiagonal.delta_eq._simp_1_9, 9303903170692057158, "[`u_1]"),
    (`ZhangLS.Spec.FixedHDiagonal.paper_diagonal, 1889903890627038117, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.paper_diagonal_c2, 11681138210937248475, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.paper_scaled_shift, 17909448478084612030, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.paper_scaled_shift._simp_1_2, 8761793513768935246, "[]"),
    (`ZhangLS.Spec.lemma83PaperBeta.eq_1, 1443403368267293299, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.cyclic_coefficient, 12152508240622280967, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.cyclic_coefficient._simp_1_1, 8761793513768935246, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.firstKernel, 9107763408899960357, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.firstKernel.eq_1, 18319700009308772241, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.pure_imaginary_product, 14114046501980321877, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaledShift, 1709274547312145803, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_1, 14568674335733737352, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_2, 14591836391070541801, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_3, 14647379146910394343, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaledShift._proof_4, 11184229512403634637, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaledShift.eq_1, 10985457501836878364, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.scaled_diagonal, 5507056268830349389, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.secondKernel, 2151808005328389746, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.secondKernel.eq_1, 5972707434505235478, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail, 3813597731881437160, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail._simp_1_1, 18215517620106685895, "[`u_2]"),
    (`ZhangLS.Spec.FixedHDiagonal.integral_deriv_tail_c2, 198549266045072950, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.tail, 9309642140688906305, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.tail.eq_1, 10434430519181518868, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.tail_continuous, 13107322374281489097, "[]"),
    (`ZhangLS.Spec.FixedHDiagonal.tail_hasDerivAt, 2641730963167347545, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_paper_admissible, 1845118262908685956, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_paper_admissible_eventually, 13291537429818921620, "[]"),
    (`ZhangLS.Spec.FixedHProfile.paperP_gt_one, 9452163801978641942, "[]"),
    (`ZhangLS.Spec.FixedHProfile.upper_window_le_paper_cutoff, 17364793170502196190, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta, 6981336687108325974, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta.eq_1, 17257263199183948575, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_contDiff, 8625012773849653212, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_derivative_at_minus_one, 10802742620571844118, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_derivative_contDiff, 18444520530692834595, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_derivative_hasCompactSupport, 348086927847381849, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_derivative_tsupport, 9974543143526699496, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_eq_glue, 12445418588207127248, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_hasCompactSupport, 825989101378255851, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_midpoint, 9200054493812774196, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_midpoint_pos, 8751117442213507162, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_support, 6082808958334082349, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_support._simp_1_1, 4396321093038226294, "[`u_1, `u_3]"),
    (`ZhangLS.Spec.FixedHProfile.beta_support._simp_1_2, 5058837530523902529, "[`u_1]"),
    (`ZhangLS.Spec.FixedHProfile.beta_third_derivative_not_zero, 14949754906134645865, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_tsupport, 2789658730468528932, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0, 6981336687108325974, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0.eq_1, 4598485268448961802, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_abs_le_one, 15402179771685154864, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_contDiff, 16969664431674478400, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_deriv_square_intervalIntegrable, 2772433783555561105, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_hasCompactSupport, 14952291094235246692, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_not_zero, 5944910672228229863, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_square_integral_pos, 18437417545654914453, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_square_intervalIntegrable, 17372088340863449313, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_tsupport, 10314933020349070300, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_third_abs_bddAbove, 1163891165436395591, "[]"),
    (`ZhangLS.Spec.FixedHProfile.beta_third_abs_le_normalization, 1407449199093389009, "[]"),
    (`ZhangLS.Spec.FixedHProfile.fixedLambda, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.FixedHProfile.fixedLambda._proof_1, 11956982661739715595, "[]"),
    (`ZhangLS.Spec.FixedHProfile.fixedLambda._proof_2, 2824371355270681610, "[]"),
    (`ZhangLS.Spec.FixedHProfile.fixedLambda._proof_3, 5665107791717739717, "[]"),
    (`ZhangLS.Spec.FixedHProfile.fixedLambda_pos, 18313033010323722018, "[]"),
    (`ZhangLS.Spec.FixedHProfile.normalization, 9035701922190319447, "[]"),
    (`ZhangLS.Spec.FixedHProfile.normalization_pos, 8521303507354140742, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h, 5291744586398708114, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h.eq_1, 7999805332397181160, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_eq_of_pos, 7815740173784304722, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_eq_zero_of_above, 16820351110511086952, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_eq_zero_of_below, 16859831598181861181, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_norm_le_one, 9463219946562133076, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_support_finite, 11445894635329217070, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_support_rpow, 13759894356772092717, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_support_window, 4828942136204478423, "[]"),
    (`ZhangLS.Spec.FixedHProfile.h_zero, 9892633904024739797, "[]"),
    (`ZhangLS.Spec.FixedHProfile.F0_endpoints, 157788684165184404, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f, 2732931413018661285, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f._proof_1, 15548198765314755609, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f._proof_2, 12495542951265472791, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f._proof_3, 13775836928741719872, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f.eq_1, 9749697540696854088, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_abs_le_one, 9879787733433939104, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_contDiff, 17585805453840544585, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_endpoints, 15814379062368324771, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_eq_zero_of_ge, 6624788014291177930, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_eq_zero_of_le, 4198934287043982999, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_hasCompactSupport, 8883249439404867708, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_not_zero, 14231092843291864691, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_support, 9395603507095711917, "[]"),
    (`ZhangLS.Spec.FixedHProfile.f_tsupport, 1949341983276134239, "[]"),
    (`ZhangLS.Spec.FixedHProfile.supported_endpoints, 9188854518130635349, "[]")
  ]
  let mut seen : Array (Name × Name) := #[]
  for (name, ci) in env.constants do
    if let some idx := env.getModuleIdxFor? name then
      let owner := moduleNames[idx]!
      if owners.contains owner then
        if seen.contains (owner,name) then
          throwError "Duplicate module-owned declaration {name}"
        if ci.isAxiom then throwError "Owned axiom {name}"
        let axs ← collectAxioms name
        unless axs.all (fun a => a == ``propext || a == ``Classical.choice || a == ``Quot.sound) do
          throwError "Nonstandard transitive axiom at {name}: {axs}"
        let typePretty ← liftTermElabM <| Meta.ppExpr ci.type
        unless expectedOwned.contains (owner,name) do
          throwError "Unexpected defining-module/name pair {owner} {name}"
        let some (_, pinnedType, pinnedUniverses) := expectedTypes.find? (fun p => p.1 == name)
          | throwError "Missing type pin {name}"
        unless hash typePretty.pretty == pinnedType do
          throwError "Full elaborated type fingerprint drift {name}"
        unless reprStr ci.levelParams == pinnedUniverses do
          throwError "Universe parameter drift {name}"
        let row := Json.mkObj [
          ("owner", toJson owner.toString),
          ("name", toJson name.toString),
          ("public", toJson (expectedPublic.contains (owner,name))),
          ("type_repr", toJson (reprStr ci.type)),
          ("type_lean_hash64", toJson (toString (hash typePretty.pretty))),
          ("type_pretty", toJson typePretty.pretty),
          ("universe_parameters_repr", toJson (reprStr ci.levelParams)),
          ("axioms", toJson (axs.map Name.toString)),
          ("used_constants", toJson (ci.getUsedConstantsAsSet.toArray.map Name.toString))]
        out.putStrLn s!"DECLARATION_JSON {row.compress}"
        out.flush
        seen := seen.push (owner,name)
  unless seen.size == 242 do
    throwError "Owned declaration count drift: {seen.size}"
  for pair in expectedPublic do
    unless seen.contains pair do
      throwError "Missing explicit declaration {pair.2}"
  unless expectedOwned.size == 242 && expectedTypes.size == 242 && expectedPublic.size == 138 do
    throwError "Incorrect pinned manifest counts"
  for pair in expectedOwned do
    unless seen.contains pair do
      throwError "Missing owned declaration {pair.2}"
  for owner in owners do
    let actual := (seen.filter (fun p => p.1 == owner)).size
    out.putStrLn s!"OWNER_COUNT {owner} {actual}"
  for mod in moduleNames do
    out.putStrLn s!"LOADED_MODULE {mod}"
  out.putStrLn s!"OWNERSHIP_TYPE_AXIOM_PASS {seen.size} PUBLIC {expectedPublic.size}"
  out.flush
