import PiEndpointObstruction

set_option pp.universes true
set_option pp.fullNames true
set_option pp.proofs false
set_option autoImplicit false

#print PiEndpointObstruction.UniformCompanions
#print PiEndpointObstruction.UniformIndependentApproximants

#check PiEndpointObstruction.endpoint_gap_lt
#print axioms PiEndpointObstruction.endpoint_gap_lt
#check PiEndpointObstruction.weak_endpoint_boundary
#print axioms PiEndpointObstruction.weak_endpoint_boundary
#check PiEndpointObstruction.no_original_endpoint_parameters
#print axioms PiEndpointObstruction.no_original_endpoint_parameters
#check PiEndpointObstruction.one_le_abs_integer_determinant
#print axioms PiEndpointObstruction.one_le_abs_integer_determinant
#check PiEndpointObstruction.determinant_error_bound
#print axioms PiEndpointObstruction.determinant_error_bound
#check PiEndpointObstruction.scaled_lower_bound_of_companion
#print axioms PiEndpointObstruction.scaled_lower_bound_of_companion
#check PiEndpointObstruction.scaled_error_identity
#print axioms PiEndpointObstruction.scaled_error_identity
#check PiEndpointObstruction.quadratic_lower_bound_of_companion
#print axioms PiEndpointObstruction.quadratic_lower_bound_of_companion
#check PiEndpointObstruction.quadratic_lower_bound_of_uniform_companions
#print axioms PiEndpointObstruction.quadratic_lower_bound_of_uniform_companions
#check PiEndpointObstruction.one_companion_independent
#print axioms PiEndpointObstruction.one_companion_independent
#check PiEndpointObstruction.companions_of_independent_approximants
#print axioms PiEndpointObstruction.companions_of_independent_approximants
#check PiEndpointObstruction.positive_quadratic_lower_bound_of_two_approximants
#print axioms PiEndpointObstruction.positive_quadratic_lower_bound_of_two_approximants
