#!/usr/bin/env python3
from pathlib import Path
import argparse, sys

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / 'ZhangLS' / 'Spec'
OUT = SPEC / 'All.lean'

def module_name(path: Path) -> str:
    rel = path.relative_to(ROOT).with_suffix('')
    return '.'.join(rel.parts)

def render() -> str:
    files = sorted(p for p in SPEC.glob('*.lean') if p != OUT)
    mods = [module_name(p) for p in files]
    header = [
        '/-',
        '  AUTO-GENERATED by tools/generate_spec_all_imports.py.',
        '  Imports every trusted ZhangLS.Spec module for isolated kernel checking.',
        '  Do not edit by hand.',
        '-/',
        '',
    ]
    return '\n'.join(header + [f'import {m}' for m in mods]) + '\n'

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    expected = render()
    if args.check:
        actual = OUT.read_text() if OUT.exists() else ''
        if actual != expected:
            print('ZhangLS/Spec/All.lean is stale; run tools/generate_spec_all_imports.py', file=sys.stderr)
            return 1
        print(f'Spec/All.lean coverage OK: {expected.count("import ZhangLS.Spec.")} modules')
        return 0
    OUT.write_text(expected)
    print(f'wrote {OUT.relative_to(ROOT)} with {expected.count("import ZhangLS.Spec.")} imports')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
